### ISSUE TITLE
Make use of NEXTCLOUD_CONFIG_DIR

### ISSUE THREAD

**Issue by tobru** [nextcloud/docker#102]
Now that version 9 is removed (#99) all available Nextcloud versions support the setting `NEXTCLOUD_CONFIG_DIR`. This could be leveraged to stop copying the Nextcloud source code to the volume during container startup in the entrypoint script (which I think is a bad practice). This would mean that the volume only contains the configuration, data, apps and themes directory. The environment variable would be configured like `NEXTCLOUD_CONFIG_DIR=/var/www/html` and PHP so that the programcode is coming from `/usr/src/nextcloud/`.

What do others think about this change?

**Comment by ChessSpider** [comment]
For this issue, also see https://github.com/nextcloud/docker/pull/23 and https://github.com/nextcloud/docker/pull/65 

![tl;dr.. yes plz](https://cdn.meme.am/cache/instances/folder290/65031290.jpg)

**Comment by SnowMB** [comment]
Yeah looks easy in the first place, but is not possible in the way nextcloud and the docker container work today.

One problem lies in the fpm image. It requires static files from the sources (images, stylesheets, ect.) to be available to the webserver, since fpm just processes php files. To make these files available outside we are using volumes. (There is the whole `/var/www/html` folder defined as volume in the Dockerfile).

But the big problem is, you can't define a volume with content in it. It doesn't matter if the volume is defined in the Dockerfile (so is part of the image) or if it's defined by the `docker run` or `docker-compose.yml` file. Every volume is created at first runtime.

That's why the source files are copied in the entrypoint script, so you get your data and source files in a volume and can share it to the webserver.

There might be another reason as well, but I can't remember it right now. :wink:

**Comment by ChessSpider** [comment]
There's also the problem that the assets seem to be scattered all over the place. There is not one or two neat /static/ folder you'll have to share, but there are multiple mixed with dirty PHP files. 

If it was one or two directories with solely static files in them, one could think about some kind of dirty work-around. But even that is not possible now unfortunately.

**Comment by tobru** [comment]
Thanks for the feedback. I see, not an easy task. Looks like this needs some more engineering. If I find a solution, I'll let you know. But there is no promise that I find something :wink:

**Comment by J0WI** [comment]
I'll close this for now. Feel free to open a PR or a new issue if you found a solution.
