### ISSUE TITLE
talk not loading properly in the latest docker image 

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/docker#1040]
## Steps to reproduce
1.pull the latest docker image
2.install talk
3.load talk

### Expected behaviour
i should be able to use talk to make conversations and groups

### Actual behaviour
it just keeps loading never finishing, i can search for contacts but that's it
the browser console is spammed with 
`Error: Request failed with status code 404 talk.js:651:9390`

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** centos

**Browser name:** Firefox

**Browser version:** 74

### Browser log

<details>
```
The javascript console log is spammed with
Error: Request failed with status code 404 talk.js:651:9390
```

</details>

## Talk app

**Talk app version:**8.0.5

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration
**Nextcloud configuration:**

<details>
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.23.32.218:6969"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "18.0.2.2",
        "overwrite.cli.url": "http:\/\/172.23.32.218:6969",
        "installed": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "maintenance": false,
        "theme": ""
    }
}


```
</details>

**Comment by sskender** [comment]
This should be fixed by installing TURN server, right?

I am currently working on adding TURN server image in my docker-compose file. If everything works as expected at the end, I am willing to create a PR.

**Comment by Fuseteam** [comment]
but it work without a turn server on 18.0.1 iiuc

**Comment by sskender** [comment]
update:

I configured turn server and video works fine, BUT only in firefox.
For some reason I can't get it to work in other browsers.

Could maybe that be your problem?

**Comment by Fuseteam** [comment]
@sskender any pointers on how to configure a turn server?

**Comment by sskender** [comment]
@Fuseteam I ran this docker image:
https://github.com/instrumentisto/coturn-docker-image

Configured coturn like wouterve did in this post:
https://help.nextcloud.com/t/setting-up-firewall-for-turn-server/42670

With minor changes:
- commented  `lt-cred-mech`
- commented `external-ip=<my external-ip>` and `server-name=mydomain.com` because my server is not directly facing the internet and ip is provided by docker (I am not running container attached to host network, rather portforwarding as I like things isolated. Although it is said this can cause problems for large port ranges, I did not face any issues myself ( so far ;) ).
- commented `no-loopback-peers` because it throws me errors otherwise
I am not sure what to do with this setting or what is for at this point, but here I can see it is allowed: https://github.com/nextcloud/vm/blob/master/apps/talk.sh
`allow-loopback-peers`

After that add your domain (without any prefixes), port and secret to talk settings in admin account.

Maybe someone could help to explain?


UPDATE:

talk works fine on android app and firefox, but not brave browser or any chromium based one

**Comment by Fuseteam** [comment]
@sskender wait would this work over vpn? mine is not facing the internet at all

**Comment by sskender** [comment]
Hmm, are all your users connected to server via VPN? In that case, as I understand it, they should act like they are on the same local network and there is no need for TURN server at all. TURN is only used to override firewall and NAT problems.

**Comment by Fuseteam** [comment]
@sskender yes they are, sounds like we were facing different issues as talk itself didn't load for me not even the text interface
it does however just work on univention...somehow
video calls feels slow on talk on univention tho but that's a separate issue, probably related to network speed

**Comment by sskender** [comment]
Yes, obviously.

After a few days of testing calls between users, browsers, android devices, conclusion is that calls mostly work fine (great picture quality), but sometimes they do not (no video or audio at all). 
There are no any changes in network or anything similar, it just looks like the technology is still a bit buggy. I will try to dig up some logs to be able to give more information.

**Comment by Fuseteam** [comment]
this is no longer an issue on 19 for me so closing
