### ISSUE TITLE
docker-compose examples: alpine versions of Nextcloud containers doesn't work with Onlyoffice document_server app

### ISSUE THREAD

**Issue by gwarf** [nextcloud/docker#1041]
Hi,
I've been trying to use the __onlyoffice__ `document_server` app with my `docker-compose` deployment based on the examples from this repository, and it seems that the document_server app doesn't work with __alpine__ containres as some binaries (like `x2t`) require a `glibc` and the __alpine__  comes with the `musl` libc.
It would be good to mention this somewhere in the doc.

In order to fix onlyoffice on my deployment I had to switch back to non alpine versions (for the nextcloud containers).

The principal source of info I found with regards this is this comment by @siccovansas: https://github.com/nextcloud/documentserver_community/issues/10#issuecomment-599009799

I've some more details on this discourse post: https://help.nextcloud.com/t/strugging-integrating-onlyoffice-with-nextcloud-fpm-alpine-mariadb-redis-cron-lets-encrypt-docker-compose/66639/2

So happy to now have onlyoffice working, thanks for all this work!

**Comment by digitalcraig** [comment]
I can confirm this issue. I was able to trace down the error from the logs as "x2t not found" (no mention of missing glibc). Once I switched the Docker image from nextcloud:18.0.3-fpm-alpine to nextcloud:18.0.3-fpm it worked. Also note that I had to chown the files on the volume because www-data between the two images has a different uid/gid:

# chown -R www-data:root /var/www
# chmod -R g=u /var/www

It really should be documented somewhere that the documentserver_community app on the non-alpine Docker image in addition to only on x86.

**Comment by J0WI** [comment]
It is mentioned here: https://github.com/nextcloud/documentserver_community#requirements

> The community document server only supports running on x86-64 Linux servers using glibc based distributions.
