### ISSUE TITLE
Question: NextCloud available in subfolder

### ISSUE THREAD

**Issue by bugsyb** [nextcloud/docker#1047]
Hi Team,

Would you please provide some guidance on how to have the NextCloud available from subfolder?

Reasoning:
- security by obscurity - for private instance, one would have to find first custom subfolder
- more apps in subfolders available.

In fact I had such config running on generic Ubuntu server, but can't get it easily running via Docker image.
Any guidance would be more than welcome.

Related to: https://github.com/nextcloud/docker/issues/57

**Comment by joshtrichards** [comment]
Hi @bugsyb  - Sorry you ran into trouble attempting this. I'm taking a pass through old Issues in this repository and yours popped up.

This was a long time ago, but the main thing that comes to mind is to do this on your reverse proxy or front-end web server (if using FPM). I'm unclear on your second point under Reasoning. If you feel so inclined, feel free to expand on that.

You also might find the [Nextcloud Help Forum](https://help.nextcloud.com) a good channel to get some ideas and feedback on this approach since it's more suited to general configuration questions. This repository is for bug reports for the official community Nextcloud Docker image itself.

If this Issue isn't relevant anymore can you please close it out?

**Comment by bugsyb** [comment]
Hi @joshtrichards ,

Whow, this is now more than 3 years and appreciate the scrub you're doing especially as it would be easier, just to close it (as too old).

I can't recall if the rev proxy was involved earlier but for sure I got it working at the end of the day with Traefik.
The trickiest part was with "well-known" portion to handle it properly.
NextCloud is put into subfolder and it is done with symboli link within the folder too pointing to "./" and Traefik as frontend catches only on subfolder.
All in all it works with little hacks and it requires me to re-generate the symbolic link after upgrades.

Hope it helps if you guys would be (hopefully will) support for sub-folder based install.

Thanks!

**Comment by bugsyb** [comment]
Ah, the reasoning - the reasoning was why do I need it and answers were provided in original posting.
