### ISSUE TITLE
Enable APCu

### ISSUE THREAD

**Issue by tobru** [nextcloud/docker#109]
Nextcloud wants to have some sort of memory caching enabled: [docs](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/caching_configuration.html). APCu is already installed in the image and ready to be used, it just needs to be activated in the Nextcloud configuration:

```
'memcache.local' => '\OC\Memcache\APCu',
```

I propose to have this pre-configured in the image, just like the app paths in `apps.config.php`. I'd add a new file `apcu.config.php` and add this setting there. What do others think about this proposal?

```
<?php
$CONFIG = array (
  memcache.local' => '\OC\Memcache\APCu',
);
```

**Comment by githtz** [comment]
Can confirm this works, thanks for the information! Should be active by default imho. Sounds like a good suggestion to me.

**Comment by SnowMB** [comment]
What happens if in the "main" `config.php` another caching solution is configured and we add a file with APCu? Does anybody know that?

The apps configuration is crucial for updating, but enabling APCu would just be for ease of use. If there are conflicts with existing configurations / switching the option, we should at least document that.

But I definetly would like to add that.

**Comment by tilosp** [comment]
@SnowMB 
I would just add a file called `apcu.config.php` to the` /usr/src/nextcloud/config` folder.
This means it will be only copied to the `/var/www/html/config` folder if it is a new docker setup. And already existing setups will be untouched.

**Comment by tobru** [comment]
Thanks a lot @tilosp for taking care of this!
