### ISSUE TITLE
我用docker-compose.yml同时部署nextcloud与onlyoffice在同一台服务器上总是出现403错误

### ISSUE THREAD

**Issue by kevinzu007** [nextcloud/docker#1090]
我用docker-compose.yml部署nextcloud、onlyoffice在同一台服务器上（http），然后前端使用nginx做反向代理（两个不同域名，https），然后配置onlyoffice connector，总是提示403错误，如下（因为app中的onlyoffice很差，所以只能另外部署一个）：

> Error when trying to connect (Client error: `GET https://nextcloud-onlyoffice.zjlh.lan/cache/files/conv_check_1264469321_docx/output.docx/check_1264469321.docx?md5=8EKqpgzOuBexTVvHqfnvnw&expires=1587542851&disposition=attachment&filename=check_1264469321.docx` resulted in a `403 Forbidden` response: <html> <head><title>403 Forbidden</title></head> <body bgcolor="white"> <center><h1>403 Forbidden</h1></center> <hr> (truncated...) )

**Comment by joshtrichards** [comment]
Hi @kevinzu007 - This is a configuration issue of some sort and, in any case, appears to be with OnlyOffice not the Nextcloud Docker image.

This repository a bug reporting and enhancement request channel for the official community Nextcloud Docker image set. Since this is not a general technical support channel, not every request receives an individual response.

I realize this is old, but in case you experience a similar problem again, I suggest posting at the [Nextcloud Help Forum](https://help.nextcloud.com/). That's the place to go for assistance regarding configuration/installation and general troubleshooting.

I'm sorry you never saw a response to this here and I hope you found help in the meantime elsewhere!

Please close this Issue out unless you disagree with my assessment of the situation. Thanks!

**Comment by kevinzu007** [comment]
ok
