### ISSUE TITLE
external storage to local docker mounts

### ISSUE THREAD

**Issue by flower1024** [nextcloud/docker#1091]
Hello,
i use external storage for other docker containers which need to change files.

my problem is that docker uses bind mounts for different volumes. so it takes a VERY long time to move large files from that local storage to the normal storage.
~~another problem is that nextcloud is unable to move directories as it insists to rename them instead of moving - something that is not possible between mounts~~

i'd suggest you change the VOLUME ["/srv/www/html" ] to /var/www. that way we can mount subdirs of that directory and they are on the same mountpoint from fpm-alpine point of view.

~~it also would be nice to change the uid of www-data. but this can easily done outside your dockerfile. see attached dockerfile as an example
[Dockerfile.log](https://github.com/nextcloud/docker/files/4532556/Dockerfile.log)~~

**Comment by lucasbasquerotto** [comment]
I'd like to suggest to [remove the VOLUME directive](https://stackoverflow.com/questions/41935435/understanding-volume-instruction-in-dockerfile/62068396#62068396) and give the consumers of the image the option to use volumes where they want (which is trivial with `-v`), instead of forcing in a specific path.

**Comment by joshtrichards** [comment]
Hi @flower1024 - I'm following up on old issues. A few responses below. Part of the reason this probably didn't get a response is because it's really more appropriately split into 4 separate issues. :-)

> i use external storage for other docker containers which need to change files. my problem is that docker uses bind mounts for different volumes. so it takes a VERY long time to move large files from that local storage to the normal storage.

I don't follow. Why can't you just point your configured volumes at your real storage? Also, you don't have to use bind mounts. Can you provide your Docker Compose file?

> another problem is that nextcloud is unable to move directories as it insists to rename them instead of moving - something that is not possible between mounts

This is an upstream matter for NC Server, not the Docker image. That said, addressed in nextcloud/server#38623

> i'd suggest you change the VOLUME ["/srv/www/html" ] to /var/www. that way we can mount subdirs of that directory and they are on the same mountpoint from fpm-alpine point of view.

Can you be more specific? Maybe provide a use case or example Compose file of a scenario you're thinking this would solve?

> it also would be nice to change the uid of www-data. but this can easily done outside your dockerfile. see attached dockerfile as an example

Added in #1812.

**Comment by joshtrichards** [comment]
Closing due to insufficient information to do anything else actionable here (and due to age).
