### ISSUE TITLE
Support for Watchtower

### ISSUE THREAD

**Issue by bottee** [nextcloud/docker#1120]
To be able to use [Watchtower](https://github.com/containrrr/watchtower) to update the Nextcloud Dockerfiles from the [examples](https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles) automatically it would be great if they could be put to Docker Hub as official containers.

**Comment by treed593** [comment]
I am going to add a vote to this

**Comment by joshtrichards** [comment]
Hi @bottee - Those examples are specifically meant for people that want to run their own custom images. It wouldn't make much sense for them to have official versions in DockerHub. That said, there is nothing stopping you from individually uploading your own customized images to DockerHub/etc.

Another possibility is to monitoring the base (official) image, since that's the only time those other Dockerfiles would be rebuilt (well, other than when you make changes locally but presumably you'd also know an update is needed during those situations. :-)

This also looks relevant to your situation:

https://www.reddit.com/r/selfhosted/comments/129bowf/how_to_build_a_docker_image_and_still_use/

**Comment by joshtrichards** [comment]
Closing:

- this is out-of-scope for the Docker image repository as the referenced examples are by definition customized images so we can't provide them
- there is nothing stopping you from individually uploading your own customized images to DockerHub/etc.

Thanks for your contributions!
