### ISSUE TITLE
How to rotate the `nextcloud.log` and limit its disk usage?

### ISSUE THREAD

**Issue by vdeville** [nextcloud/docker#1154]
Hello,
I don't see logrotate rule for nextcloud.log in the docker image. That is normal ? my file is growing, do i need to map to /dev/stdout for docker log management ?
Thanks

**Comment by doc75** [comment]
@MyTheValentinus, on my side I am rotating the log on the host, and it seems to work.
Here is the configuration I am using to integrated this in logrotate.

I assume that the file `nextcloud.log` is located on your host under `/mnt/nextcloud/data/nextcloud.log` (configuration below to be adapted).

Content of `/etc/logrotate.d/nextcloud`:

```
/mnt/nextcloud/data/nextcloud.log {
  monthly
  rotate 12
  missingok
  notifempty
  compress
  delaycompress
  postrotate
    touch /mnt/nextcloud/data/nextcloud.log
    chown 82:82 /mnt/nextcloud/data/nextcloud.log
    chmod 640 /mnt/nextcloud/data/nextcloud.log
  endscript
}
```

Hope this helps.

**Comment by stellarpower** [comment]
Could some sort of default be setup, or this be mentioned in the instructions? I'm using the FPM image, and I've only got about 4G of data, and I have been running out of space, only to find my log file is 19G in size, and on warn level logging.

**Comment by joshtrichards** [comment]
The parameter you are looking for is `log_rotate_size` and it's a Nextcloud Server parameter (`config.php`). It's not Docker image specific, but works well with it because it configures Nextcloud to handle it's own log rotation. The docs cover it here:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#log-rotate-size

Please use the Nextcloud Help Forum: https://help.nextcloud.com if you wish to follow-up on this. That's the best channel for general troubleshooting or configuration assistance. This repository (here) is solely for bug reporting and enhancement ideas specific to the Docker image.

I'm going to close this Issue out since it's been sitting open for ~3 years. :-) Good luck (and see you at the forums hopefully)!
