### ISSUE TITLE
Set install location

### ISSUE THREAD

**Issue by UMB8998** [nextcloud/docker#1171]
Hello
I have a server where there is a container with ngnix web server, which serves multiple php websites and I want to integrate nextcloud using the fpm image on the server, the problem is that the install defaults to the /var/www/html/ directory. There is any way that you guys implement a variable where we could set the install dir?
I guess that i could change the dockerfile and dockerentry.sh but it will be very hard to change it every time we get an update
Thank You
P.S. this is an amazing project

**Comment by doc75** [comment]
@UMB8998 , not sure to understand the problem you are raising, so please forgive me if my answer is not relevant.
On my side, I am mounting the /var/www/html directory to a host directory and then my NGINX uses this same directory in read only. So for me there is no need for such a variable; But again I might be missing something.

Perhaps you should provide more information on how you launch your container and try to link it to NGINX so that we better understand your need.

**Comment by lmarianski** [comment]
I if I'm reading this right, i have the same issue, I'm trying to host Nextcloud behind a reverse proxy w/ subfolder paths, and thus I need to change the base URL the app sits at, but changing the OVERWRITEWEBROOT env var points NC at the new path, but doesn't actually make the app install to the specified directory, causing a redirect loop

**Comment by lmarianski** [comment]
FYI i posted a solution to the aforementioned issue
