### ISSUE TITLE
With redis env config for docker need to check for false

### ISSUE THREAD

**Issue by mnestor** [nextcloud/docker#1179]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Use redis without a password
2. Errror loading web. Also in occ `RedisException: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? in /var/www/html/lib/private/RedisFactory.php:94`

### Expected behaviour
Tell us what should happen
Site should load and occ should not error

### Actual behaviour
Tell us what happens instead
Errors!

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
19.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Docker image update

**Where did you install Nextcloud from:**
Docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

This check should also look for the value being false as set by getenv() when you don't set a password. Otherwise it runs trying to set a password and redis connection fails.
https://github.com/nextcloud/server/blob/b219eadb8f3f459f2c71e937dfd3542f0792da8e/lib/private/RedisFactory.php#L93

There are probably other areas this needs to be checked as well.

**Comment by makayabou** [comment]
I modified redis.config.php, but i still get error message.

Otherwise, I have this in config.php : 
```
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redisnext',
    'port' => 6379,
    'password' => false,
  ),
```

**Comment by siccovansas** [comment]
For those who use Nextcloud's [with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml) and run into an internal server error since today; you need to configure `volumes` and `command` for your `redis` service in your `docker-compose.yml`, e.g. like this:

```
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
```

Also in `docker-compose.yml` in the `app` service add the following environment variable below `REDIS_HOST=redis`, where you set a Redis password:

```
  REDIS_HOST_PASSWORD=<REDIS_PASSWORD>
```

In the same directory as your `docker-compose.yml` you then create `redis.conf` and add the following line:

```
requirepass <REDIS_PASSWORD>
```

You can now run `docker-compose up -d` again and visit your Nextcloud in your browser. If it says that you are in maintenance mode then edit your `config/config.php` file and change `maintenance` to `false` and run `docker-compose restart`. You can then manually run the 19.0.1 update and all should be fine again :).

**Comment by alexpovel** [comment]
Next to the solution by @siccovansas , there is a one-liner as found [here](https://nickjanetakis.com/blog/docker-tip-27-setting-a-password-on-redis-without-a-custom-config) that works without a `volume` and without `redis.conf`:

In `docker-compose.yaml`, for the nextcloud app itself, do the usual:

```yaml
  app:
    ...
    environment:
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: yourpassword
    depends_on:
      - redis
      - ...
```

and for the redis cache it is sufficient to call:

```yaml
  redis:
    image: redis:alpine
    command: redis-server --requirepass yourpassword
```

This works and gets rid of the errors of nextcloud/server#21913.

However, as soon as there is even a single additional option to be passed to redis, this approach quickly falls apart and using a static `redis.conf` file and mounting it as usual will be the better approach, which is why I went with that as well.

**Comment by SlavikCA** [comment]
My (temporary) solution is to use the previous version of Redis:
```
  redis:
    image: redis:5-alpine3.12
    ...
```

**Comment by Fixmetal** [comment]
> ```yaml
> --require
> ```

Thanks.
For those stumbling on this who don't want to have a clear text password in `docker-compose.yml` here's a solution:

```
# yq r docker-compose.yml  services.redis.env_file
- redis.env

# yq r docker-compose.yml  services.app.env_file
- redis.env
- db.env
- smtp.env

# yq r docker-compose.yml  services.redis.command
/bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"

# cat redis.env 
REDIS_HOST_PASSWORD=insertYourPasswordHere
```
