### ISSUE TITLE
Correct examples - fix known problems

### ISSUE THREAD

**Issue by Lejo1** [nextcloud/docker#1275]
The first time to install nextcloud on docker using docker-compose and ran into multiple problems.

So let's have a look at the [maxi-install](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm) example with nginx + letsencrypt, fpm, mariadb, redis, cron

So let's look at the problems a new noob like me had:

1. #927 as this is a letsencrypt setup the :$server_port is not needed
2. #819 just add OVERWRITEPROTOCOL=https same here it's a letsencrpyt setup so it's always https
3. [redis needs a password](https://help.nextcloud.com/t/solved-latest-docker-image-broke-the-installation-redis-password-auth/87598/2) marked/mentioned
4.  #1041 should be at least mentioned if not fixed
5. I didn't knew what installation to chose, there should be some more explanation on the setups.

A docker-compose file should be a working easy install solution. We don't want everybody searching again for already known problems.

**Comment by etique57** [comment]
Thanks, I just ran into 5, 3 and 4 respectively. For 4, I'd still prefer to use the OnlyOffice separate docker but cannot seem to make it work.

**Comment by Lejo1** [comment]
> I'd still prefer to use the OnlyOffice separate docker but cannot seem to make it work.

Same here, there should also be an example for that as well.

**Comment by cacack** [comment]
I'll chime in here that I've been running NextCloud in a docker-compose setup based on the [with-nginx-proxy/mariadb-cron-redis/fpm](/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm) arrangement for a while and have managed to keep it running over the years.  However, some recent changes with the mobile app authentication (nextcloud/android#4786) have led me to revisit my compose in an attempt to fix -- and now I'm completely hosed with HSTS warning.

It would be _very_ helpful if the examples were solid so that I could use them as a basis for my setup.  As they currently stand, I'm going to need to invest some serious time to dig out of this mess.

**Comment by Polyterative** [comment]
I tried for hours and was unable to create a usable environment...

**Comment by joshtrichards** [comment]
Most of the above Issues in the overview have been addressed various ways. The examples have also been streamlined. There is still work to be done, but there are various Issues tracking existing known bugs as well as enhancement plans/ideas for the remaining examples.

If you have further problems, please use the Nextcloud Help Forum - https://help.nextcloud.com - to troubleshoot, but feel free to report suspected bugs in new dedicated issues (for each bug) here.

Existing (known/reported and unfixed) bugs can also found by searching the "examples" label: https://github.com/nextcloud/docker/issues?q=is%3Aopen+is%3Aissue+label%3Aexamples
