### ISSUE TITLE
Cannot connect to MariaDB from graphical install wizard

### ISSUE THREAD

**Issue by manzari** [nextcloud/docker#129]
I fail to setup NextCloud from [docker-compose example](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose.yml). The graphical install wizard seems to be unable to connect to MariaDB. Error message "_SQLSTATE[HY000] [1130] Host '172.19.0.6' is not allowed to connect to this MariaDB server_" is given.

**Context**
I am using Ubuntu 16.04.2 LTS
Docker has been installed like described in their documentation, version is: 17.06.0-ce
Docker-compose is version 1.8.0

**Process**
1. clone docker compose examples from git
2. fill in missing variables
3. run docker-compose up
4. browse the web service
5. enter database credentials as in compose file
6. error message is displayed

**Expected result**
graphical install wizard should continue without error

**Current result**
following error is displayed:
 _SQLSTATE[HY000] [1130] Host '172.19.0.6' is not allowed to connect to this MariaDB server_

**Comment by manzari** [comment]
I don't know what did the trick but I guess it was something with the creation of root and nextcloud users. However, for me this issue is fixed. I'll return if I know the exact reason.

**Comment by jkemming** [comment]
I know this issue is pretty old by now, but I stumbled upon the exact same issue and was able to (hopefully correctly) solve it.
With some minor 10.x version of MariaDB, they seem to have changed the default behaviour for allowing connections from IPs other than localhost, which in my case meant that version 10.0 worked out of the box together with Nextcloud whereas the newest version (10.4) resulted in the same `Host 'xxx.xxx.xxx.xxx' is not allowed to connect to this MariaDB server` error.
This is caused by the `bind-address` configuration (see [here](https://mariadb.com/kb/en/library/configuring-mariadb-for-remote-client-access/) for further details), but it can be configured to allow connections from any origin. To do so, just append `--bind-address=0.0.0.0` to the `command` property in your `docker-compose.yml` file.

**Comment by flowercow** [comment]
I met the same problem. 
got the docker-compose example and file the blank area if needed.
docker-compose up -d and met this.
docker-compose version is 1.24, all. these in omv 4.21 which worked as an nas based on debian.
I also try manually set up nextcloud with docker, only use nextcloud: latest and mariadb, it works fine.
this problem sound like the mariadb set the database Administrator user can be only connected from localhost. 
but i think this example compose example file has been tested, it should work. fine.
