### ISSUE TITLE
Nextcloud 20.0.4 not available on hub.docker.com

### ISSUE THREAD

**Issue by hansingt** [nextcloud/docker#1331]
Currently, the Nextcloud 20.0.4 image builds are failing and thus are not available on https://hub.docker.com/_/nextcloud.

Could you please take a look at this and provide the new images? Currently, Nextcloud is constantly complaining, about a new version beeing available, which I can't install because of missing images.

**Comment by DudleyDursley** [comment]
I have tried building the fpm-alpine image locally using Podman (I don't have Docker installed). The build process gets stuck because `pecl install` is prompting for all kinds of stuff. Replacing `pecl install` with `yes "" | pecl install` (it's kind of hacky, I know) will allow the build to complete but I don't know if this will result in a proper configuration.

**Comment by GuidoDr** [comment]
it is still not yet available there. Let's hope that it still will get available this week.

**Comment by calistoc** [comment]
it is not there yet but building the new image worked fine to me, I did upgrade to 20.0.4 and all looks ok
hopefully I’m not missing anything as I never build the nextcloud image by myself and I have always used the images from hub.docker.com

**Comment by RobinFrcd** [comment]
Looks like [nextcloud:20.0.4](https://hub.docker.com/layers/nextcloud/library/nextcloud/20.0.4/images/sha256-3982dd35b31af337b27ddd755e4cf88ae1c6c36460e1561cbb5158f9e00a0489?context=explore) is now available on docker hub.

Thank you for the update :+1:
