### ISSUE TITLE
Talk/Spreed app default installation to HTTP

### ISSUE THREAD

**Issue by Xelendor1** [nextcloud/docker#1350]
I am using SWAG image with Nextcloud/latest image.  When I install the talk app, no matter what I do the URL defaults to http://nextcloud/apps/spreed/ instead of https://nextcloud/apps/spreed/ .  The only way to fix this issue is to forward port 80 to port 443 from my firewall to my nextcloud instance, but since all the other apps work just fine, I think it is just a syntax error in the docker file.  Might be good to fix this in the next update so all data can be run through port 443 on the firewall.  once the port 80 data is forwarded to 443 on the swag proxy it automatically switches the http to https like it is configured to.

**Comment by joshtrichards** [comment]
Hi @Xelendor1 - Thanks for the report. I don't believe this is a Docker image matter. We don't even have anything specific to talk/spreed. I suspect this was either a bug in Spreed or a configuration matter. Since this was awhile ago it may have been resolved. If not, I suggest reporting this issue to the Spreed repository/developers.

If you agree with my assessment, please close this Issue out here. Thanks!
