### ISSUE TITLE
NEXTCLOUD_ADMIN_* ignored in env-file

### ISSUE THREAD

**Issue by kitkittia** [nextcloud/docker#1360]
I have this env-file:
```
#/home/me/nc_env
MYSQL_ROOT_PASSWORD=mysql_root_password
MYSQL_DATABASE=nextcloud
MYSQL_USER=nc_admin
MYSQL_PASSWORD=mysql_nc_password
MYSQL_ALLOW_EMPTY_PASSWORD=no
MYSQL_HOST=127.0.0.1
NEXTCLOUD_ADMIN_USER=nc_admin
NEXTCLOUD_ADMIN_PASSWORD=nc_password
```

When I run `podman run -d --env-file=$HOME/nc_env nextcloud:latest`, I get a "Create an **admin account**" page. I was expecting a login page at this point.

**Comment by waredsystems** [comment]
I confirm. For me, it's not only ignored, it doesn't work anymore.

With this docker-compose.yml:

`version: '3.7'
services:
  database:
    image: mariadb
    container_name: nextcloud_database
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=password1234
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - lan
    volumes:
      - db:/var/lib/mysql

  nextcloud:
    depends_on:
      - database
    image: nextcloud
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=database
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=password1234
    networks:
      - lan
    volumes:
      - html:/var/www/html

volumes:
  db:
  html:

networks:
  lan:`

I get:
`Initializing nextcloud 20.0.4.0 ...
Initializing finished
New nextcloud instance
Installing with MySQL database
starting nextcloud installation
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
 -> 
retrying install...`

If I remove NEXTCLOUD_ADMIN_USER and NEXTCLOUD_ADMIN_PASSWORD, it's working!

Thanks for your help

**Comment by zimmertr** [comment]
NEXTCLOUD_ADMIN_USER and NEXTCLOUD_ADMIN_PASSWORD are also not working for me.

**Comment by TBG-FR** [comment]
Same issue here

**Comment by joshtrichards** [comment]
```
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
 -> 
retrying install...
```

What came up in the log after this?

10 seconds after this it would have retried to connect. The entrypoint tries 10 times with 10 second breaks in between before it gives up. This is specifically in there to handle situations where the db container is still setting itself up.

The initial db connect is much more likely to fail when using `NEXTCLOUD_ADMIN_*` because specifying these variables triggers a fully automated setup. This means as soon as the Nextcloud container boots it tries to connect to the database. Whereas in a non-automated setup (i.e. when those variables aren't specified), there is zero interaction with the database until you manually visit the setup web interface.

**Comment by joshtrichards** [comment]
These variables definitely work today.

Feel free to ping us (preferably in a new Issue with key details like the container startup log) if you experience problems today.
