### ISSUE TITLE
Usage of variables for mount paths not working

### ISSUE THREAD

**Issue by cgraaaj** [nextcloud/docker#1375]
I wanted to create folder based on user name in the external storage, as suggested in [this] doc (https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage_configuration_gui.html)
![image](https://user-images.githubusercontent.com/36030305/105217603-161bf200-5b7a-11eb-82d8-c469f6a70835.png)
But i couldn't able to achieve it, am getting the below ! mark
![image](https://user-images.githubusercontent.com/36030305/105217623-1ddb9680-5b7a-11eb-8213-9cf8dc01d0ca.png)
without $user variable there is no error
![image](https://user-images.githubusercontent.com/36030305/105217641-2502a480-5b7a-11eb-848d-e37946ca6e15.png)

Am using nextcloud 20.0.5 in docker 20.10.2

**Comment by joshtrichards** [comment]
Hi @cgraaaj - Sorry to hear you ran into difficulties. I realize this is an old issue, but this sounds like a support request so that's likely why it got overlooked. This venue is for reporting bugs in the community Nextcloud Docker image. It is not for issues with Nextcloud itself nor for general troubleshooting/technical support queries.

Your query sounds like a perfect topic to bring up at the [community help forum](https://help.nextcloud.com).  

If you agree with my assessment, please close your Issue out here. Thanks!

**Comment by joshtrichards** [comment]
Hi @cgraaaj - A follow-up with some additional info, but I'm still going to close this issue out now since it is not a Docker image matter. It's an NC Server config and documentation matter and. I worked an issue like this not too far back and figured out what was going on. Here are the notes: 

See nextcloud/documentation#10948

I suggest following up there if you have more to add about the matter before it gets documented better.
