### ISSUE TITLE
Add Support for MySQL / MariaDB SSL Support with autoconfiguration

### ISSUE THREAD

**Issue by KornKalle** [nextcloud/docker#1392]
Hello all,

I just started the migration from a dedicated instance, to a docker setup which should include SSL Support for the database connection, but I could not find the option to enable SSL for the Database connection.

We are using a dedicated Galera Cluster with Read-Write Splitting as recommended by Nextcloud for larger Setups.

Did I miss a config parameter or is there another way to enable this out of the box?

**Comment by joshtrichards** [comment]
Unfortunately nextcloud/server#19738 is a blocker for this. Feel free subscribe to (and/or upvote) that upstream issue. When/if that's addressed then the image could consider support for it. For now, it's a "won't fix" IMO because it's effectively impossible for the image to handle it cleanly without Nextcloud Server supporting it at install time.

It *is* possible to enable SSL (switch to it) yourself after installation (i.e. after the first boot that generates your permanent `config.php` ). 

It *may* be possible to use the image's auto config hooks mode to achieve this today in an automated manner as workaround, but I haven't tried it.
