### ISSUE TITLE
Question Regarding Secrets and TRUSTED_PROXIES

### ISSUE THREAD

**Issue by smokemyshoes** [nextcloud/docker#1450]
Hi

Fairly new to docker so please bear over with me...

I'm trying to deploy the base apache image as outlined in the readme [here](https://github.com/nextcloud/docker), but I'm having some issues getting it all up and running. I'm not done investigating myself so this is not a support request as such. However I do have a few questions that I hope you can help me with.

1. I want to run my nextcloud container behind a nginx reverse proxy (the swag container from linuxserver.io) on the same docker network. How do I use TRUSTED_PROXIES env. variable? Can I refer to the container by it's name (swag) or do I have to specify its IP? and how do I pass the value, i.e do I need to put brackets, quotation marks or similar?
2. Regarding docker secrets: Is it true that MYSQL_ROOT_PASSWORD is not supported as a secret or is it just an oversight in the paragraph just below the secrets example in the readme?
2. Also regarding docker secrets: In the same paragraph just below the secrets example, it says that that MYSQL_DB is supported but in the "base apache" example further up the env. variable is called MYSQL_DATABASE so what is the correct name for this secret?

Many thanks in advance...

**Comment by joshtrichards** [comment]
1. If you're Docker network is all private IPs you may not need configure anything at the Docker level: 

https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol

But if you do:

> TRUSTED_PROXIES (empty by default): A space-separated list of trusted proxies. CIDR notation is supported for IPv4.

Also see https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html#defining-trusted-proxies

3. `MYSQL_ROOT_PASSWORD` is a variable for the MySQL/ MariaDB container not the Nextcloud container so you'd have to check their documentation. 
4. I don't see a reference to `MYSQL_DB` today so I presume that has since been fixed.
