### ISSUE TITLE
How to Stop the Default NextCloud Initializing when First Lauch

### ISSUE THREAD

**Issue by guoguoguilai** [nextcloud/docker#1499]
I installed NextCloud by running `docker run -d -p 8080:80 nextcloud`  and it was awesome. I did a lot configuraion on my nextcloud instance, and now I want to bring all of the container to another place. So I packed the local image and push it to my Docker Hub, and run docker pull in another server. 

However, everytime I run docker run in another serve, the new nextcloud instance would initialize again. How can I stop the Initialization?

**Comment by JuniorJPDJ** [comment]
Container image doesn't have any of your settings...
It's just image of clear, unmodified, unconfigured nextcloud.
Please - before doing issues under projects using docker, read ANYTHING about how docker works.

You have your data placed under volumes created on your host.
You didn't name them or bind-mount, so migration will be pain.

Next time do a lil research, then configure things ;)

**Comment by joshtrichards** [comment]
Hi @guoguoguilai - Please read the documentation closer to understand how to set up persistent storage. The way you're running the image isn't appropriate for more than a quick test run. 

In any case, this isn't a general technical support channel - it's only for bug reports in the Docker image. This query/discussion is better suited to https://help.nextcloud.com. Feel free to continue it there.

If you agree with my assessment, please close this Issue out so that we can keep it focused on bug reports and to avoid confusion. Thanks!

**Comment by joshtrichards** [comment]
Closing per my last comment.
