### ISSUE TITLE
Doctrine\DBAL\Schema\SchemaException: An index with name 'ts_docid_lastcontact' was already defined on table 'oc_text_sessions'.

### ISSUE THREAD

**Issue by diegobraions** [nextcloud/docker#1508]
...while upgrading from 18.0.14 to 19.0.12 ( all over docker ).

Thk.

**Comment by diegobraions** [comment]
Fix it.

ALTER TABLE oc_text_sessions DROP INDEX ts_docid_lastcontact

**Comment by joshtrichards** [comment]
Hi @diegobraions - Thanks for the report and glad you found a workaround. Your report didn't get far here since it's not a Docker image bug. This repository is only for Docker specific bugs. In the future, this type of query should be reported upstream to the [Nextcloud Server](https://github.com/nextcloud/server) repository. 

If you agree with my assessment and/or this is no longer an issue, please close this Issue out here. Thanks!

**Comment by joshtrichards** [comment]
Closing per my last comment.
