### ISSUE TITLE
Hiding index.php in URL for Apache

### ISSUE THREAD

**Issue by mahnunchik** [nextcloud/docker#151]
Colud you please hide `index.php` in the URL in the Apache image by default.

**Comment by SnowMB** [comment]
Just FYI: Updating it manually just needs 2 simple steps:

Add these line to your `config.php`:
```
...
'htaccess.RewriteBase' => '/',
...
```

And then run from your host: 
```
docker-compose exec -u 33:33 web /var/www/html/occ maintenance:update:htaccess
```

To integrate this in the image is not that easy, because the occ command requires to be run after the installation is made. We don't have a possibilities yet to run scripts after the initial installation (which is triggered when you finish the installation page in your browser).

We made changes to skip the installation page (see #147), but running the installation is still triggered by opening nextcloud in the browser. 

@tilsop any idea on a simple solution?

**Comment by tilosp** [comment]
I found a simple solution take a look at #152.

**Comment by PurlingNayuki** [comment]
```
docker-compose exec --user 33:33 web /var/www/html/occ maintenance:update:htaccess
```
works for me instead of `-u` option.
