### ISSUE TITLE
Cron job is causing zombie processes

### ISSUE THREAD

**Issue by 10bias** [nextcloud/docker#1512]
I am running nextcloud in docker with docker compose. The cron container is causing zombie processes. Here the related part of my docker-compose.yml

```  cron:
    image: nextcloud:21.0.2-apache
    restart: always
    volumes:
      - /home/tobias/nextcloud/nextcloud_nextcloud:/var/www/html
      - /home/tobias/nextcloud/nextcloud_apps:/var/www/html/custom_apps
      - /home/tobias/nextcloud/nextcloud_config:/var/www/html/config
      - /home/tobias/nextcloud/nextcloud_data:/var/www/html/data
    entrypoint: /cron.sh
    networks:
      - nextcloud
      - web
    depends_on:
      - db
      - redis
    labels:
      - "traefik.enable=false"
```

After a while running this container there a some zombie processes related to the nextcloud cron container:

```
33      1562  0.0  0.0   2324   568 ?        Ss   Jun04   0:00  \_ busybox crond -f -l 0 -L /dev/stdout
33        8498  0.0  0.0      0     0 ?        Z    Jun04   0:00      \_ [sh] <defunct>
33       20385  0.0  0.0      0     0 ?        Z    Jun04   0:00      \_ [sh] <defunct>
33       26941  0.0  0.0      0     0 ?        Z    Jun04   0:00      \_ [sh] <defunct>
33       28291  0.0  0.0      0     0 ?        Z    Jun04   0:00      \_ [sh] <defunct>
33       31126  0.0  0.0      0     0 ?        Z    Jun04   0:00      \_ [sh] <defunct>
33       17041  0.0  0.0      0     0 ?        Z    Jun04   0:00      \_ [sh] <defunct>
33       25403  0.0  0.0      0     0 ?        Z    01:00   0:00      \_ [sh] <defunct>
33        1143  0.0  0.0      0     0 ?        Z    02:55   0:00      \_ [sh] <defunct>
33        7506  0.0  0.0      0     0 ?        Z    04:15   0:00      \_ [sh] <defunct>
33       11952  0.0  0.0      0     0 ?        Z    05:15   0:00      \_ [sh] <defunct>
33       14875  0.0  0.0      0     0 ?        Z    05:55   0:00      \_ [sh] <defunct>

```

Does anyone have same problems or a solution for this?

Best regards!

**Comment by joshtrichards** [comment]
Hi @10bias - I'm going older Issues in this repository that are still open. Hopefully you were able to find help through a different channel.  I haven't run across any similar reports in this repository so I don't believe this is a bug in the Docker images (but anything is possible). I suggest checking the logs and digging into what background jobs you have running in your Nextcloud installation. Perhaps one added by an app is behaving strangely. This query is probably best suited for https://help.nextcloud.com since this isn't a general troubleshooting channel.

If this Issue is no longer relevant, can you you close the Issue here in this repository? Thanks!

**Comment by joshtrichards** [comment]
Closing per my last comment.
