### ISSUE TITLE
Migration path or best-practice from :22-apache to :production-apache

### ISSUE THREAD

**Issue by Nimrod-666** [nextcloud/docker#1568]
Hi, i would like to migrate my current 22-apache installation to the production-apache tag in the future and i wanted to ask if there's a best practice to do this. My plan is:

1. Setting my image tag to "nextcloud:22.1-apache" to freeze the nc-version to 22.1.*
2. Wait until a version newer 22.1 will get into the production tag
3. Set production-apache as my image tag source

Would that be an acceptable way to switch to the production tag?

**Comment by J0WI** [comment]
The production channel is discontinued: https://github.com/nextcloud/updater_server/commit/946ae1b79fd78d8cf8ce8063caccdd7dc4f09844

**Comment by meonkeys** [comment]
@J0WI could you explain why `production` and `stable` were removed? I'm not against the change, I'm just trying to understand it. I'm running 21 right now and am looking into 22. One question I've got is how much longer 21 will be supported because I'm not sure why I should upgrade to 22 yet.

(see also: #1561 )

**Comment by Nimrod-666** [comment]
@J0WI i would be interested in the idea behind removing production and stable too. I thing it would be cool to have a tag that stays on an old version until it's not supported anymore, and only moves to a newer version after that.
