### ISSUE TITLE
docker run -d -p 8080:80 nextcloud:23 with all default options but still getting a non working CODE server

### ISSUE THREAD

**Issue by Utopiah** [nextcloud/docker#1659]
Hi,

I run my own NextCloud instances on my local machine for testing and on my server. Unfortunately I can't manage to get collaborative editing. I noticed with [the recent Hub II announcement](https://nextcloud.com/blog/nextcloud-hub-2-brings-major-overhaul-introducing-nextcloud-office-p2p-backup-and-more/) that there is now NextCloud Office. I thought I would try again.

I ran the most simple example, namely `docker run -d -p 8080:80 nextcloud:23`, connect to it via http://localhost:8080, create my admin login and accept the suggest services, which seems to include CODE. I let the process end and everything seems to work.

Unfortunately I can't edit rich documents and when I head to http://localhost:8080/settings/admin/richdocuments I get `Could not establish connection to the Collabora Online server.`, cf below : 

![image](https://user-images.githubusercontent.com/1076655/146276478-6a10f72b-823b-4f55-9582-de21a139db27.png)

So at this point I'm a bit confused. When few months ago I tried the same setup with docker-compose I thought that maybe I missed something. Here though, as it seems to be all included and managed, I fail to see what I could have done wrong.

I checked the browser console, even tried another browser (but as it is server side I don't see how it could be related) and the container logs but can't see anything special, no error.

I noticed https://github.com/nextcloud/docker/issues/1164 but opened another issue as that seems related to another setup relying on compose.

**Comment by Utopiah** [comment]
Do these [requirements from Collabora Online](https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/) still apply?

- A host that can run a Docker container
- A subdomain or a second domain that the Collabora Online server can run on
- An Apache server with some enabled modules (NGINX instructions in a blog here)
- A valid SSL certificate for the domain that Collabora Online should run on
- A valid SSL certificate for your Nextcloud

Because if so then I imagine a default subdomain is being used. It also means without properly configuring the reverse proxy to provide certificates for 2 subdomains it will not work, despite the installation instruction not mentioning this.

**Comment by J0WI** [comment]
I'd not recommend to run Collabora in the same container as Nextcloud. https://github.com/nextcloud/docker/pull/630 might be useful for you.

**Comment by Utopiah** [comment]
Thanks, I might try again. I specifically tried version 23 because of the integration / bundling because before, via compose, it also didn't work for me. Everything starts properly yet when it's time to use Collabora, unable to connect. I imagine there is some reverse proxy parameter I might miss. It's a shame that somehow default settings for this don't "just" work.

**Comment by bertin0** [comment]
I see everywhere that you use a separate domain for collabora, but nobody explains why/if this is mandatory, as the collabora server is on another port anyways. Any clue?

**Comment by tribut** [comment]
I've left some comments what you need to do in order to get the built-in CODE server to run at https://github.com/nextcloud/docker/issues/1896#issuecomment-1558810330

**Comment by joshtrichards** [comment]
> Unfortunately I can't edit rich documents and when I head to http://localhost:8080/settings/admin/richdocuments I get Could not establish connection to the Collabora Online server.,
[...]
> I checked the browser console, even tried another browser (but as it is server side I don't see how it could be related) and the container logs but can't see anything special, no error.

The place to look to troubleshoot this sort of situation would be your `nextcloud.log` not the container log.

Since you were using a non-default port, you may have simply encountered this (which would have been in your Nextcloud log):

`ConnectException cURL error 7: Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:8080/custom_apps/richdocumentscode/proxy.php?req=/hosting/capabilities`

The reason is because `localhost` means different things from your container's perspective than it does from your host's perspective. The only port reachable within the container would be :80 not :8080.

To follow-up on this, I suggest the help forum (https://help.nextcloud.com) and/or if there seems to be a bug in the activation process for `richdocuments`, open an issue in that repo (https://githubt.com/nextcloud/richdocuments)

> Do these [requirements from Collabora Online](https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/) still apply?

Those requirements apply mostly for install methods other than the *Built-in* one.

I'm going to close this, since this isn't an image specific matter and there's nothing here to be done about this.
