### ISSUE TITLE
Docker image through portainer stuck in preparing

### ISSUE THREAD

**Issue by gpampel** [nextcloud/docker#1661]
I have been previously using nextcloud docker image: nextcloud: 22-apache. 
I updated my overall server the other evening and once all my stacks resumed - only nextcloud did not restart.
I ran an initial mysql check on the database image - this was initially cause the DB container to crash, but by running a repair on the nextcloud db it seems to have fixed it self. 

I then, deleted the full stack and tried to make a new stack with the same nextcloud version. 
The container remained in the preparing state - I have understood that means it is trying to pull the image. 
I then forced a pull from the command line to get the image so that my stack would look locally prior to pulling down from docker hub.

I have tried a few times and the container does not start. All other services work perfectly. 
Some information on the environment:
Nextcloud is deployed as a stack due to a swarm configuration (currently the swarm is only a master node)
I use portainer to deploy my stacks and I have previously had this working

I do note that the images on docker hub are currently failing could this be the reason?
I also subsequently tried to use:
nextcloud: 23-apache - sticks in preparing
nextcloud: 22.2.3-apache - sticks in preparing
nextcloud: 22-fpm-alpine - sticks in preparing

Nothing it written to the logs that I can find.

I also checcked whether the issue relating to database versions could be the problem. 
My version was 10.5. I have however made sure to lock it down to this version

**Comment by joshtrichards** [comment]
Hi @gpampel - Sorry to hear you ran into difficulty. I'm processing older Issues still open in this repository. I don't see any evidence of image problems around the time period of your report. I think whatever this was was a local environment matter. (particularly since it sounds like your db container crashed).

I hope were were able to find assistance through other channels - such as the [Nextcloud Community Help Forum](https://help.nextcloud.com) - which is better suited for general support and troubleshooting matters.

If this matter is no longer relevant and you agree with my assessment, can you close this Issue out here to avoid confusion? Thanks!

**Comment by joshtrichards** [comment]
Closing per my prior comment.

**Comment by gpampel** [comment]
Happy it is closed.
