### ISSUE TITLE
stable channel is not upgraed to version 23

### ISSUE THREAD

**Issue by mabeett** [nextcloud/docker#1694]
I see stable channel in [generate-stackbrew-library.sh](https://github.com/nextcloud/docker/blob/master/generate-stackbrew-library.sh#L4)  continues on Nextcloud version inversion 22.2.3 administration overview web page suggests upgrading to release 23.0.0.

What does this repository need in order to do upgrade the release channel?
How could we help?

Thanks in advance,

**Comment by major-mayer** [comment]
I would be also interested why this is still not updated.
Especially since the second minor update is released now.

**Comment by Mailblocker** [comment]
Same question from my side. Is there a blocking point to do this?

**Comment by dharmann** [comment]
> Same question from my side. Is there a blocking point to do this?

I'm unable to retrieve the original link where I've read this, but that I've followed to resolve the issue:
breiefly (as described [here](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html#using-the-command-line-based-updater)), you can upgrade using terminal:
`sudo -u <YOUR_WEB_USER> -g >YOUR_WEB_GROUP> php updater/updater.phar`

**Comment by Mailblocker** [comment]
@dharmann how does this solve a docker tag problem?

**Comment by dharmann** [comment]
> @dharmann how does this solve a docker tag problem?

I'm sorry, but I don't use the docker version. I've installed NC from scratch

**Comment by x86dev** [comment]
I'm also wondering why this isn't updated ... Nextcloud 23 GA is out since quite some time. Can anybody shed some light on this, please?

**Comment by Zottel92** [comment]
The stable-tag  of nextcloud_docker normaly is applied to the stable version of nextcloud after its 100% roullout.

When nextcloud_server names a new stable version, the rollout happens in waves.
The percentages of updated can be seen here:
https://github.com/nextcloud/updater_server/blob/master/config/config.php

So Version 23 is now 100% stable since about 7 days, so I expect the nextcloud_docker stable-tag to shift to a 23 version in the nearer future.

**Comment by J0WI** [comment]
changed in https://github.com/nextcloud/updater_server/pull/728 and https://github.com/nextcloud/docker/pull/1738
