### ISSUE TITLE
When trying to add SSL Support, container closes...

### ISSUE THREAD

**Issue by Ciangi** [nextcloud/docker#170]
Hello,

i would like to add HTTPS support in my docker, but You create docker image that init process is Apache, so when i type
a2enmod ssl
i have to
service apache restart

but when i type it container closes.
What should i do in this case?

Greetings.

**Comment by SnowMB** [comment]
You can restart the whole container. But there are a few things to consider when you add funcionality to the container:

Containers in docker are meant to be thrown away at some point. All configuration and data should be made persistant either by being part of the image or stored in volumes.
Recreating and updating will remove any changes to the container, because the new container will be created based of the image. So you really should create your own image instead of just making changes to the running container. You can do this by creating a so called dereived image using nextcloud as base image. We give some examples of how you do this in the [readme](https://github.com/nextcloud/docker#adding-features) and in the [examples](https://github.com/nextcloud/docker/tree/master/.examples) section.

Another thing you could do is leaving the nextcloud container as it is and adding a reverse proxy in front that handles all the https encryption. We have got an [example](https://github.com/nextcloud/docker/tree/master/.examples#with-nginx-proxy) for that as well.
