### ISSUE TITLE
SMTP API keys not working

### ISSUE THREAD

**Issue by philipt4** [nextcloud/docker#1836]
Nextcloud Installed with docker, all features working properly other than the SMTP email under basic settings.
Using Mailjet which supports smtp ports 25, 587, 465 with or without ssl.
Using API keys for my login that work with other services such as bitwarden is throwing errors in the Nextcloud UI.
Currently looking at ways to overload the smtp settings with symfony/mailjet since the use of api key and secret key wont be accepted as username/password in nextcloud.

**Comment by joshtrichards** [comment]
Hi @philipt4 - Your report is kind of vague (no version, no specific error message), but this doesn't like a Docker image issue anyway. This repository here is only for Docker specific bug reports, not general Nextcloud ones. Nor is it for general troubleshooting assistance. I'd suggest https://github.com/nextcloud/server or even https://help.nextcloud.com/

If you agree with my assessment of your report, please close this Issue here to avoid confusion. Thanks!

P.S. Based on what I see at https://dev.mailjet.com/smtp-relay/overview/ I see no reason why you can't put the contents of `$MJAPIKEYPUBLIC` as your login in NC and of `$MJAPIKEYPRIVATE` as your password.

Note the email configuration of NC did change a bit relatively recently:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html

**Comment by joshtrichards** [comment]
Closing as per my prior comment. Feel free to return if you think this is related to a bug in the Docker image itself. Good luck!
