### ISSUE TITLE
Use flock for the upgrade lock

### ISSUE THREAD

**Issue by remram44** [nextcloud/docker#1903]
In #1757, an attempt was made at replacing the locking mechanism for upgrade (when running multiple containers) from simply creating a file to using Linux advisory locks with flock. Admittedly the patch had a few flaws.

Eventually the MR was closed in favor of making the locking optional with an environment variable in #1760. This is a very different approach, but it resolves the issue you had at the time, #1742.

I am opening this issue to gauge whether the is still interest in using flock rather than the mere presence of the file, e.g. did you close #1757 because you don't want to do that, or simply because it was not ready and another patch was able to fix the pressing upgrade issue in #1742?

Pros of using flock:

* If a container crashes or is stopped during upgrade, another container can do the upgrade. Right now if locking is enabled, you will have to manually go into the volume and remove the file.
* A concurrent container waiting to do the upgrade will be able to get the lock immediately, rather than the next time it "polls" after sleeping for a while.

Cons of using flock:

* If a container crashes during upgrade, another container can do the upgrade. I don't know if it is safe to resume an aborted upgrade (but at the same time, what else can you do?)
* It requires the volume to support locks (but even NFS, Cephfs, ... support it, so you'd have to use a weirdo non-POSIX-compliant filesystem)
* A bit more complexity in the entrypoint script

**Comment by remram44** [comment]
I would love a "yay" and "nay" on this before I dig into the test failure at #1905 :sweat_smile:

**Comment by meonkeys** [comment]
I closed #1757 because @skjnldsv's change meant I could just ignore / work around the problem by not using `NEXTCLOUD_INIT_LOCK`.

"Yay" from me to continue work on this. I'm not a maintainer, just a Nextcloud enthusiast/contributor. It would be a Good Thing to use some kind of ephemeral lock rather than the one requiring user intervention. If `flock` works let's do it (assuming the maintainers agree/approve).

> but even NFS, Cephfs, ... support it

Ah, this removes some of the uncertainty around my patch in #1757, thanks.

Good call to put the lockfile in `/var/www/html`, I messed that up in #1757.

**Comment by meonkeys** [comment]
re: this con:

> If a container crashes during upgrade, another container can do the upgrade. I don't know if it is safe to resume an aborted upgrade (but at the same time, what else can you do?)

Agreed. In either case you'll have a broken server and would need to inspect the logs for errors.
