### ISSUE TITLE
Remove javascript sources map files (*.js.map) to reduce images size

### ISSUE THREAD

**Issue by Adphi** [nextcloud/docker#1914]
Why are the sources map files included in the image ?

In the latest *fpm-alpine* image we can see:

```sh
$ du -hs /usr/src/nextcloud/
535.5M  /usr/src/nextcloud/

$ find /usr/src/nextcloud -name '*.js.map' -exec rm {} \;
$ du -hs /usr/src/nextcloud/
396.5M  /usr/src/nextcloud/
```

We can save 139M, and also decreases boot time. 
Even more so if we remove the source map files from all the `/var/www/html` as this will also remove the plugin ones:

In the latest *apache* image:
```sh
# install the dummy instance
$ su www-data -s /bin/sh -c "./occ maintenance:install --admin-user=admin --admin-pass=admin"
# install some apps
$ for app in mail calendar contacts tasks spreed; do su www-data -s /bin/sh -c "./occ app:install $app && ./occ app:enable $app"; done
# take a look at the size
$ du -hs / 2> /dev/null
2.0G    /
# remove sources map
$ find /usr/src/ -name "*.js.map" -exec rm -f {} \;
$ find /var/www/html/ -name "*.js.map" -exec rm -f {} \;
# take a look at the size again
$ du -hs / 2> /dev/null
1.5G    /
```

**Comment by skjnldsv** [comment]
Hey, same answer than https://github.com/nextcloud/server/issues/36536 :wink: 

> They are included because only then JS errors are useful.

Otherwise you cannot debug any issue you might face. Map files are only fetched when you use the dev tools.
I'm not sure the docker image size is such a big deal tbh :)

**Comment by ChristophWurst** [comment]
The browser doesn't load those files unless needed for a stack trace. If anything, this will make our developer's life a lot harder if we can no longer read error traces.

**Comment by MoritzGlantz** [comment]
Hey! Checking in after some time. Shipping source maps might not add up to the loaded files, but to the overall foot print of Nextcloud itself. I just checked my Nextcloud instance and it had 1GB of source map files there with no actual use since I don’t develop Nextcloud. I just use it.

And this adds up since backups also contain all these files.

I wrote a [forum post](https://help.nextcloud.com/t/js-sourcemaps-in-production/222799) about this as well as a little [mastodon thread](https://mastodon.social/@MoritzGlantz/114342079235619262).

Why am I looking at the storage Nextcloud needs? I am using Nextcloud on Uberspace which only has 1GB of storage. I am mostly using it for calendar, maps and other apps. Not so much for file storage. So disk space is a rare resource there and I regularly get quota wanings when doing Nextcloud updates.

It’d be very cool if we could do something about this. May be a toggle in the setting for a dedicated developer mode?

**Comment by MoritzGlantz** [comment]
They get shipped to various instances and may never get used. I had no use for them in over ten years. Personally I don‘t think that justifies taking up so much space.

**Comment by ChristophWurst** [comment]
Thank you for your feedback

**Comment by cederberg** [comment]
Don't know if this is viable for the Nextcloud build chain, but an alternative would be to link to a CDN for these files. Might be a trade-off worth doing, although it would break the locally hosted paradigm (for errors and debug sessions).

Lots of Nextcloud packages are already on NPM, so it could look like this for example:

```
//# sourceMappingURL=https://cdn.jsdelivr.net/npm/@nextcloud/capabilities@1.2.1/dist/index.mjs.map
```
