### ISSUE TITLE
when running via quadlet apache errors with could not open error log file /var/log/apache2/error.log.

### ISSUE THREAD

**Issue by Lunarequest** [nextcloud/docker#1970]
Quadlet is an opinionated tool for easily running podman system containers under systemd in an optimal way. I have found through this that when `--log-driver=passthrough` is used apache can't start up and complains that `/var/log/apache2/error.log` doesn't exist. I  believe this is due to `/var/log/apache2/error.log` being a symlink to STDOUT which doesn't exist with the passthrough driver.

The workaround I have found is to mount `/var/log/apache2/` to some folder, in my case i use a TMPFS mount but this is not ideal and a better solution would be a solution in the image itself.

**Comment by joshtrichards** [comment]
What sort of solution do you envision?

Also, these seem potentially relevant:
* https://github.com/containers/podman/issues/17692
* https://github.com/containers/podman/discussions/17348

**Comment by Lunarequest** [comment]
> What sort of solution do you envision?

Ideally the image should detect it is running without access to STDOUT+STDERR and fall back to some sort of compact

> * [rootless containers non root workloads can't write to /dev/stdout nor /dev/stderr containers/podman#17692](https://github.com/containers/podman/issues/17692)

this is relevant ^
> * [How to read container's stdout when using passthough log driver? containers/podman#17348](https://github.com/containers/podman/discussions/17348)

this is not relevant ^

**Comment by joshtrichards** [comment]
We won't be adding support for this at this time since it's being done like this by our upstream image (the official PHP Docker image):

https://github.com/docker-library/php/blob/e5d6f311d3162ef1440914c05130a4280a719f52/Dockerfile-linux.template#L121-L125

Also also because it is easy enough to override, as you discovered. You could also set your Compose file to build a custom image derived from this one. And implement your changes there:

https://github.com/nextcloud/docker#adding-features
