### ISSUE TITLE
Allow custom upload folder configuration for Docker container

### ISSUE THREAD

**Issue by realies** [nextcloud/docker#2019]
This would optimise upload delays that happen when moving files between volumes. It will also prevent filling the docker volume when attempting to upload a file larger than it.

**Comment by joshtrichards** [comment]
Do you mean the `tempdirectory`? Because AFAIK there's no such thing as a configuration directive for an "upload folder" in Nextcloud.

e.g. 

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#tempdirectory

**Comment by joshtrichards** [comment]
Related: #1680
