### ISSUE TITLE
Copy file webdav

### ISSUE THREAD

**Issue by karilca** [nextcloud/docker#2021]
okay, i dont really know im fixing right thing. my problem is that. after while when transfering file i get that. Translate: there is problem when copying file in davs://Karlo@nextcloud.o...arlo.tk/-remote.php/webdav. HTTP error: connection terminated unexpetedly

**Comment by joshtrichards** [comment]
Hi @karilca - Can you please post this issue on the [Nextcloud Help Forum](https://help.nextcloud.com)? You'll probably get a better response there since this sounds like a general support/configuration issue. I also suggest - when you do so - including the stack trace/log entry from your `nextcloud.log` along with some other details like what client you're using for your connection.
