### ISSUE TITLE
DNS Resolution broken between nextcloud 25 and 26

### ISSUE THREAD

**Issue by EliRibble** [nextcloud/docker#2049]
I'm testing with the following:

```
> sudo podman run -it --rm --entrypoint /bin/bash  --network slirp4netns:port_handler=slirp4netns nextcloud:25-apache
root@aaf03f02b25c:/var/www/html# curl -s https://amionline.net | head -n 2
<!doctype html>
<html lang="en" class="h-100">
root@aaf03f02b25c:/var/www/html# exit
exit

> sudo podman run -it --rm --entrypoint /bin/bash  --network slirp4netns:port_handler=slirp4netns nextcloud:26-apache
root@81b12e09bc59:/var/www/html# curl -s https://amionline.net | head -n 2
root@81b12e09bc59:/var/www/html# curl -v https://amionline.net
* getaddrinfo() thread failed to start
* Could not resolve host: amionline.net
* Closing connection 0
curl: (6) getaddrinfo() thread failed to start
```

Looks like there's a break in the DNS resolver between 25 and 26, at least in my setup.

**Comment by joshtrichards** [comment]
Hi @EliRibble - Thanks for the report. I'm unable to reproduce this though in Docker:

```
josh@debian1:~$ docker run -it --rm --entrypoint /bin/bash nextcloud:25-apache
root@b9ec51944a59:/var/www/html# curl -s https://amionline.net | head -n 2
<!doctype html>
<html lang="en" class="h-100">
root@b9ec51944a59:/var/www/html# exit
exit
josh@debian1:~$ docker run -it --rm --entrypoint /bin/bash nextcloud:26-apache
root@faff9de481c7:/var/www/html# curl -s https://amionline.net | head -n 2
<!doctype html>
<html lang="en" class="h-100">
root@faff9de481c7:/var/www/html# 
```

Perhaps some local environment matter or something specific to podman/slirp4netns or your specific configuration.

**Comment by EliRibble** [comment]
Thanks for checking, I was able to locally build version 27 and get it working with a single change:

```
diff --git a/27/apache/Dockerfile b/27/apache/Dockerfile
index f43c575..f97799a 100644
--- a/27/apache/Dockerfile
+++ b/27/apache/Dockerfile
@@ -1,5 +1,5 @@
 # DO NOT EDIT: created by update.sh from Dockerfile-debian.template
-FROM php:8.2-apache-bookworm
+FROM php:8.1-apache-bullseye

 # entrypoint.sh and cron.sh dependencies
 RUN set -ex; \
```

With that, DNS resolution is fixed for me using the same test.

I assume this is actually a bug with the upstream image.

**Comment by siccovansas** [comment]
I'm also dealing with this issue. It seems to happen since Nextcloud 26.0.4 (though not on fpm-alpine) when combined with an older Docker version.

Here are my findings when running `curl` and if it doesn't give the `curl: (6) getaddrinfo() thread failed to start` error: 
- Docker 19.03.13 + Nextcloud 26.0.3: ✅
- Docker 19.03.13 + Nextcloud 26.0.4: ❌
- Docker 19.03.13 + Nextcloud 26.0.4-fpm: ❌
- Docker 19.03.13 + Nextcloud 26.0.4-fpm-alpine: ✅

- Docker 20.10.17 + Nextcloud 26.0.3: ✅
- Docker 20.10.17 + Nextcloud 26.0.4: ✅
- Docker 20.10.17 + Nextcloud 26.0.4-fpm: ✅
- Docker 20.10.17 + Nextcloud 26.0.4-fpm-alpine: ✅

Note that all these Nextcloud images are using PHP 8.2.8.

Is updating Docker the only way out or was there a change on Nextcloud's part that resulted in this issue that can be fixed?

(Not sure if it is related but I can [a Docker issue](https://github.com/moby/moby/issues/42680) mentioning this error.)

**Comment by EliRibble** [comment]
```
> sudo podman run -it --rm --entrypoint /bin/bash --net host php:8.2-apache-bookworm
root@home:/var/www/html# curl https://amionline.net
curl: (6) getaddrinfo() thread failed to start
```

I need to create an image to use `debian:bookworm-slim` since it doesn't have `curl`...

**Comment by EliRibble** [comment]
Looks like I have other issues creating a working image related to an old version of `podman` - I won't be able to follow up on this for days.

**Comment by EliRibble** [comment]
Thanks, `buildpack-deps:bookworm-curl` also fails for me. Seems to clearly _not_ be a problem with Nextcloud.

**Comment by joshtrichards** [comment]
The Docker Engine is up to v24.0.5 at this point. There have been various odd network and DNS related issues that have cropped up and been addressed. Sometimes they don't become a problem until some other container OS bit gets updated... then they appear. It's important to track DE changes that might be relevant:
https://docs.docker.com/engine/release-notes/24.0/
