### ISSUE TITLE
UMASK for external local storage (linked via volumes)

### ISSUE THREAD

**Issue by ChillDuder** [nextcloud/docker#2069]
Hello,

as mentioned in title:
is there any possibility to set umask for the nextcloud process in the container?

New files created with nextcloud on external storage use umask 0022, which means read for non-group users/others. 

To test I tried to add a script to set in /docker-entrypoint-hooks.d/before-starting/
also tried to modify entrypoint.sh and add umask in the beginning also just before exec '$@" at the end. Nothing helped.

Any idea?

Thank you very much

**Comment by d-uzlov** [comment]
Nextcloud overrides environment umask with umask value from config:
You can fix it by changing `config.php` in some way, or by adding a custom config file:

```bash
cat << EOF > /var/www/html/config/umask.config.php
<?php
\$CONFIG = array (
    'localstorage.umask' => 0,
);
EOF
```

I prefer the separate config file because this way I can configure it even before installation using a pre-installation hook script.

Source: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#localstorage-umask

**Comment by ChillDuder** [comment]
Oh, great! 
Thank you very much!

it never occurred my mind to look in nextcloud docs, because i was inclined to fixed that on OS/docker level.
