### ISSUE TITLE
example docker-compose files contain wrong environment variable

### ISSUE THREAD

**Issue by lucascherzer** [nextcloud/docker#2072]
The docker-compose.yml files in `.examples/docker-compose/insecure/` (both apache and fpm) contain the environment variable `MYSQL_ROOT_PASSWORD` which will not work as the database (mariadb) expects the value in `MARIADB_ROOT_PASSWORD`.

To fix this:
Change the variable name from `MYSQL_ROOT_PASSWORD` to `MARIADB_ROOT_PASSWORD` in the following files:
- `.examples/docker-compose/insecure/apache/docker-compose.yml`
- `.examples/docker-compose/insecure/fpm/docker-compose.yml`

**Comment by joshtrichards** [comment]
Can you elaborate on what lead you to suspect this? If this is in fact occurring it's an issue that needs to be addressed in the [MariaDB docker image repo](https://github.com/MariaDB/mariadb-docker) because both variable prefixes are officially still documented by MariaDB:

https://hub.docker.com/_/mariadb/
https://github.com/docker-library/docs/tree/master/mariadb#environment-variables

It would be a tremendous breaking change to drop support for `MYSQL_` entirely on their part so I suspect something else is going on here.

I see no indication in the history of their `docker-entrypoint.sh` that support has been dropped:

https://github.com/MariaDB/mariadb-docker/commits/master/docker-entrypoint.sh
