### ISSUE TITLE
Location of default nginx.conf file for the FPM Docker-compose example?

### ISSUE THREAD

**Issue by robclay** [nextcloud/docker#208]
I understand that using the docker-compose exampe (Base version - FPM)  from https://hub.docker.com/_/nextcloud/ does not work, and you manually need to move / do something with the nginx.conf.  

Can someone tell me how to get the file that the original creators wanted to use from the default page on https://hub.docker.com/_/nextcloud/ using the FPM example?  I can then try to manually put it in a folder and point my nginx to it, and see if I can get something started...

Thanks for any advice.

**Comment by SnowMB** [comment]
It seems to me that there is a misunderstanding what the fpm image is.

This image does not contain a webserver. It just contains the php fastcgi process manager and the nextcloud installation. We can think about this as a kind of backend for our nextcloud. 

So to use this image there is an additional web server needed to serve request from the internet. There is no way to talk directly to the fpm container. So one possibility is to use a nginx Webserver as explained in the examples. This would be our frontend.

Since we use the default nginx image we have to tell nginx that he has to forward web requests to the backend (fpm) container.
In the [examples](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose) section you can find this file.

**Comment by robclay** [comment]
SnowMB - Thank you!

A few things that may help someone reading this with a QNAP - I saw the examples earlier, but saw the 'Version 3' at the top of the compose file and skipped them, as the QNAP only allows Version 2.  However, the commands in [here](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure/mariadb/fpm) are Version 2 compatible.  Just change the 3 to a 2 at the very top of the file.
