### ISSUE TITLE
How to migrate to NextCloud AIO docker version

### ISSUE THREAD

**Issue by fan8956** [nextcloud/docker#2093]
Hi I have been using nextcloud docker image for a while and would like to migrate to the AIO docker version. But I could not find any doc around that. Could someone provide some help plz? Thanks in advance.

**Comment by joshtrichards** [comment]
The AIO Docker image has its own repository:

https://github.com/nextcloud/all-in-one

And they have a FAQ entry for your question:

https://github.com/nextcloud/all-in-one#how-to-migrate-from-an-already-existing-nextcloud-installation-to-nextcloud-aio

Also potentially relevant since Nextcloud's standard migration/backup/restore processes are relevant:

https://docs.nextcloud.com/server/latest/admin_manual/maintenance/migrating.html

Follow-ups probably best handled there (aio) or the Nextcloud Help Forum - https://help.nextcloud.com
