### ISSUE TITLE
Does Cronjob is preinstall on the image, background cron.php?

### ISSUE THREAD

**Issue by Piceeeeeee** [nextcloud/docker#2135]
Hello,
After a lot of research i am wondering if it's a image issue,:
So, i have install NC, with docker.yml trough portainer, nothing fancy just a basic nc container, but it seem that cron.php, the back ground job isn't running at all, i can't find any people with the same issue ON docker, which lead me to the question, does someone know how is cron.php running, trought cronjob? If it is, i dont have cronjob preinstall on the image, so before going and making a custom image, does someone has a lead? 
step done : tried both redis and apcu check compatibility and permission +user, cron.php.

**Comment by Piceeeeeee** [comment]
if nothing, i am gonna delete the issus, thank you if you take the time to read

**Comment by joshtrichards** [comment]
You can either use a dedicated cron container (see https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml) or call "docker compose exec [...]" from your a cron entry on your host. You can either search past since closed issues or check the Nextcloud Help Forum - https://help.nextcloud.com - to get help.
