### ISSUE TITLE
cron missing in image

### ISSUE THREAD

**Issue by jclsn** [nextcloud/docker#2136]
I think it would be great if cron could be added to the image. This is needed for e.g. the thumbnail generation plugin and it is tedious to always rebuild your own image for every update.

**Comment by joshtrichards** [comment]
There's no need to build a custom image. There are numerous ways of addressing this, but the simplest approach is a cron job on the host. 

E.g. https://github.com/nextcloud/previewgenerator/issues/176#issuecomment-558008337

**Comment by tzerber** [comment]
> There's no need to build a custom image. There are numerous ways of addressing this, but the simplest approach is a cron job on the host.
> 
> E.g. [nextcloud/previewgenerator#176 (comment)](https://github.com/nextcloud/previewgenerator/issues/176#issuecomment-558008337)

To extend this reply: 
Most docker instances nowadays have a [separated "cron" container that offloads the cron jobs](https://github.com/nextcloud/docker/blob/8afd97014cc3445e888a165f8c2d16af7ed036aa/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml#L45)  since some of those are quite intensive and can block the PHP proccess for long time. 

That container is basically the same NC instance that uses the `cron.sh` docker entrypoint. 
Instead of using the applications's container, a more "portable" solution is to use the cron container and/or it's crontab. 

To do so : instead of using the main container name, use the cron container name to execute the same task, for example (copied from link above) `0 22 * * * root cd /docker/nextcloud/ && /usr/local/bin/docker-compose exec -T --user www-data cron php occ preview:pre-generate`. 

Other options include mounting the file  `/var/spool/cron/crontabs/www-data` as volume, and putting the desired crontab entries there. With recent including of the watch parameters of Docker, you don't need to do anything additional.

<sup><sub>And i should probably make an example of this feature, because it's quite a powerful feature that is not used around here, and it should be.</sub></sup>

**Comment by jclsn** [comment]
Okay, thank you for clearing that up :)
