### ISSUE TITLE
PHP-FPM UID + GID incompatible with Nginx UID + GID

### ISSUE THREAD

**Issue by almereyda** [nextcloud/docker#2204]
When using the Nextcloud image with the supplied Compose example there will be errors with retrieving files from the file system.

The error will be similar to:

    stat() "/var/www/html/custom_apps/mail/img/mail.svg" failed (13: Permission denied)

as described in [Proper permissions after upgrade/migration? - ℹ️ Support / 📦 Appliances (Docker, Snappy, VM, NCP, AIO) - Nextcloud community](https://help.nextcloud.com/t/proper-permissions-after-upgrade-migration/111278)

It is useful to `chown -R 33:101` the volume mapped into both containers for mitigation.

References:

https://github.com/nextcloud/docker/blob/473af1bed11c84866b31e2d5ebc39bc87070b758/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml#L25

https://github.com/nextcloud/docker/blob/473af1bed11c84866b31e2d5ebc39bc87070b758/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml#L39

https://github.com/nextcloud/docker/blob/473af1bed11c84866b31e2d5ebc39bc87070b758/28/fpm-alpine/entrypoint.sh#L99-L100

https://github.com/nginxinc/docker-nginx/blob/1f227619c1f1baa0bed8bed844ea614437ff14fb/mainline/alpine-slim/Dockerfile#L15-L16

This extends:

- #2127

Which other strategies have people found to resolve this, eventually without chown'ing the state?

Maybe it is easier nowadays to run from Caddy #2052?

Or it is better to build an Nginx container that runs from `www-data`/`33` as well?

Surprised this hasn't come up earlier.

**Comment by tzerber** [comment]
Can you post your compose file and OS variant/version? I have updated two production instances to 29 today, both are effectively a copy-paste from the fpm-nginx example (with some stuff added) and i have no such issues, they both have a bunch of apps including mail but no permission errors.

**Comment by joshtrichards** [comment]
Are you, perhaps, using bind mounts rather than actual volumes?

Also, keep in mind that technically nginx is only serving files. It only needs read permission. FPM does all the heavy lifting, including anything that requires write permissions.

**Comment by joshtrichards** [comment]
I'm going to close this since there wasn't a response to the query for additional info >30 days ago. I suggest following up at the community help forum: https://help.nextcloud.com

**Comment by Drugoy** [comment]
> Are you, perhaps, using bind mounts rather than actual volumes? (This would be different than the examples).
> 
> It'd probably be best if you shared your actual Compose file. :-)
> 
> Also, keep in mind that technically nginx is only serving files. It only needs read permission. FPM does all the heavy lifting, including anything that requires write permissions.

I am struggling with this problem as well. I use bind mounts (because this way I may specify arbitrary paths to the binds on the host's filesystem the way I like and because... that's what I got used to).
I currently have a few problems upon upgrade, after re-creating the nextcloud container based on the newer image (27.1.3 -> 27.1.11 right now):
0. I don't use docker-compose at all, I am executing "low level" docker commands directly (like create docker network or create containers).
1. the mode problem: it seems like the image's entrypoint script copies files files from the /usr/src/nextcloud to /var/www/html with the wrong mode: I see that all files in /var/www/html have mode 600, so whatever group is owning those files - has absolutely no access to them! This is probably an indicator that entrypoint script has some bugs regarding the use of `rsync`.
2. the ownership problem: either I miss some important knowledge about docker or your scripts are wrong: nginx image from docker's public library by default runs as root and thus its main process `nginx: master process nginx -g daemon off` runs as user `root` but then forks children processes `nginx: worker process` running as less privileged user `nginx` with uid=gid=101. At the same time nextcloud's php-fpm based image also by default runs as root and thus its main process `php-fpm: master process (/usr/local/etc/php-fpm.conf)` runs as user `root`, but then also forks children processes `php-fpm: pool www` running as less privileged user: `www-data` with uid=gid=82. This introduces the ownership problem: uids and gids in these 2 images completely mismatch and so files in a bind-mount being owned by either 101:101 or 82:82 completely block access to the other user! I don't get, how am I supposed to avoid this problem? IMO, your php-fpm images should have such uid:gid for user `www-data` that match the uid:gid of user `nginx` in nginx image. But since that's not how it is now - I have to manually issue `chown`s and `chmod`s recursively for files and dirs after every version upgrade and that's why I hate this process so much right now.
