### ISSUE TITLE
Missing versioncheck.php

### ISSUE THREAD

**Issue by NicoBeyer** [nextcloud/docker#251]
I launched the current version over a version 12 data folder., that is now updated to v13 (e.g. i can't go back).

I get this errror:
Fatal error: require_once(): Failed opening required '/var/www/html/lib/versioncheck.php' (include_path='.:/usr/local/lib/php') in /var/www/html/index.php on line 31

The file versioncheck.php is missing.

**Comment by rdxmb** [comment]
@NicoBeyer What was your problem and solution?

I have the same problem here when updating to 12.7

My Workaround: copy /var/www/html/versions.php to '/var/www/html/lib/versioncheck.php' I hope this is the right file ...

**Comment by NicoBeyer** [comment]
Yes something like that. I did a blank setup and copied the data folder or something.

**Comment by rdxmb** [comment]
Seems like the update-process is not very clean here, for `/var/www/htm` l should be a volume - which means that it is mounted here with a bind mount. Of course, if a new version requires a new file within there, it is missing.
Having this within a major version (12.x to 12.0.7) is a very surprising and critical problem: Using it in swarm mode with tag `:12` breaks the setup when switching to another node.

IMHO this issue should be re-opened - to prevent that with future upgrades.

**Comment by ukos-git** [comment]
Can you check if your /var/www/html directory was correctly initialized? Otherwise copy the files manually.

**Comment by Stephane-80** [comment]
Sorry I'm new Docker user 
how to proceed on a windows version of docker?
I do not know where to find the /var/www/html directory 
Thank you

**Comment by deisi** [comment]
@Stephane-80 I had just the same issue on ubuntu using docker. Can it be, that  your aborted the initial start of your docker container?
I got the same error message due to an uncompleted initialization during the first run phase of my docker container. After deleting the persistent `nextcloud` volume and rebuilding my docker container it worked. 
I just had to wait about 10min before the web interface would show up. During that phase there was no feedback in docker or elsewhere that it was doing something.

**Comment by ukos-git** [comment]
I proposed an uninitialized status file in https://github.com/nextcloud/docker/issues/431 
If you can confirm that this is the same problem, I could integrate a status report to the entrypoint.sh.

**Comment by akorz** [comment]
Hello,
I have the same issue. Is there any news?

**Comment by FleischKarussel** [comment]
Hey guys,
I hit that 'issue' when starting for the first time and k8s restarted the pod in the middle of the copying process because the health check on port 80 timed out. :unamused:

**Comment by ukos-git** [comment]
That is exactly the problem. 
We would need a separate init container with its separate live check.

**Comment by ukos-git** [comment]
Another solution is to **not** copy the html folder At run time but create it during container build and link 3rd party app folder, config and data folder to persistent volumes. This will need 3 persistent volumes instead of only one for html but the approach would ensures data integrity of the html folder as it is reset to default on container reset.

**Comment by captn3m0** [comment]
Why does the entrypoint run rsync?

```rsync: [receiver] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(829) [receiver=3.1.2]
rsync: [sender] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(829) [sender=3.1.2]
```

Breaks everytime for me on a fresh install (`15.04-apache`). I like @ukos-git's suggestion above of not copying html at run. Containers are supposed to be immutable.

**Comment by ukos-git** [comment]
should have been closed with https://github.com/nextcloud/docker/pull/660
