### ISSUE TITLE
Dashboard cannot connect to IMAP server

### ISSUE THREAD

**Issue by awesome-manuel** [nextcloud/docker#372]
It seems the `php7.0-imap` package is missing.

See also https://github.com/nextcloud/dashboard/issues/13.

**Comment by tilosp** [comment]
imap is intentionally not installed, to keep this image small.
if you want to install it you can use this Dockerfile: https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/imap/apache/Dockerfile

**Comment by iMartyn** [comment]
@tilosp It's not really valid to close this bug and point at a "build it yourself" dockerfile for a feature that is provided by nextcloud itself.

This is a library docker image, and if the addition of the imap library in php is huge (it's not in my view) then there should be a tag built including it.  For instance, I don't want to use an apache image, I want to use the official nextcloud php-fpm image and cannot in it's current state.

Please re-open.

**Comment by SnowMB** [comment]
> I want to use the official nextcloud php-fpm image and cannot in it's current state.

Just out of curiosity, what is wrong / missing for your setup?

**Comment by iMartyn** [comment]
php-imap is missing, this means I can't auth against my imap server (which is how my owncloud is set up and I want to migrate).

**Comment by muhlba91** [comment]
@SnowMB I totally agree with @iMartyn. This is an official library image for Nextcloud and since you are already offering Dockerfiles to people having imap support included, I don't think it's a lot of effort having them integrated in automated builds to publish them alongside the other images for each release. Additionally, since it's one out of just a few additionally offered Dockerfiles I believe there is/was a need for those in the community.
Personally, I don't want to duplicate this repository, include imap support, publish images to Dockerhub and then having to maintain/merge changes and new releases each time just to be able to update Nextcloud.
Could you please reconsider including php-imap either in the current image (I also don't think it adds too much of an overhead) or integrating the image in your CI? I would even say publishing the "full" image instead of only an imap enabled one should be perfectly fine in order to let you choose between a smaller but not complete or an complete image if only this suffices. (Obviously, if someone need more than the full image version, they have to maintain it themselves.)

**Comment by tilosp** [comment]
I think that it is not that much effort to build the example Dockerfiles and publish them.
A bigger problem is that if we have to many tags the https://hub.docker.com/_/nextcloud page becomes really crowded. It already happens if there are RC and/or beta tags.

**Comment by iMartyn** [comment]
So, still, we have a **_library dockerfile_** that doesn't support a major feature of the application, and this is because "the page gets crowded"!?

C'mon people, this is not the way to do things.
