### ISSUE TITLE
Does Installing NextCloud with the Dockerfile pose any performance issues?

### ISSUE THREAD

**Issue by thedonquixotic** [nextcloud/docker#400]
Hi, designer, learning to code. I know a little front end but I'm a complete idiot when it comes to backend type stuff. Servers are.... mysterious to me. 

I was wondering if the dockerfile had any big cons over the manual install? I just want a simple to install personal cloud solution and so far I've had quite a bit of trouble with the manual install.

**Comment by SnowMB** [comment]
There is a little overhead, but it's fairly insignificant. The benefits outweigh this by far. 

See for example https://stackoverflow.com/questions/21889053/what-is-the-runtime-performance-cost-of-a-docker-container#26149994.

You don't "pollute" your host system with the server software, you just need docker. It's very easy to setup and updating / deleting is basically throwing the container away (and start another one). It's also very nice to sandbox software you want to try, that deeply integrates in your host system otherwise. With the examples given you should be running in a few minutes and if you don't like the docker approach you can get rid of it even faster.

So just try it :grin:

**Comment by thedonquixotic** [comment]
I think I will! I spent all day slamming my head against the wall with
several different apache and nginx manual install tutorials so this might
be my salvation. Thanks!

**Comment by pierreozoux** [comment]
I'll second @SnowMB :) Google were the one to contribute to the linux kernel the features to create "containers". All google infra runs on containers :)

I'll close this issue, but feel free to reopen if needed.
