### ISSUE TITLE
setup warning of security scan in Nextcloud 14

### ISSUE THREAD

**Issue by suntorytimed** [nextcloud/docker#448]
I am using a slightly modified docker-compose setup of .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/ for my server.

Since Nextcloud 14 the security scan complains about:
```
There are some warnings regarding your setup.
The "Referrer-Policy" HTTP header is not set to "no-referrer", "no-referrer-when-downgrade", "strict-origin" or "strict-origin-when-cross-origin". This can leak referer information. See the W3C Recommendation ↗.
```

Is this linked to the nginx setup inside of the container or is it a general issue with the Nextcloud fpm container?

**Comment by LouisMT** [comment]
You need to set this header in your web server. For example:

```
server {
    # Configuration
    add_header Referrer-Policy no-referrer always;
}
```

**Comment by suntorytimed** [comment]
@LouisMT thanks. I think this should be added to the nginx.conf files in the .examples

**Comment by opgailey** [comment]
@LouisMT What file exactly is it that needs to be edited to include that header?

**Comment by LouisMT** [comment]
It's your web server's configuration file. Its location and syntax depend on the web server you're using.

**Comment by suntorytimed** [comment]
@LouisMT Thanks for submitting the patch. My server is all green now :slightly_smiling_face:

**Comment by Nottt** [comment]
From Google here.

Can confirm this works, but it's weird because according to their [forum](https://help.nextcloud.com/t/the-referrer-policy-http-header-is-not-set-to-no-referrer/36613/5) they say to add it to `.htaccess` instead and it did not fix it for me.

Now I have both 2 "fixes" applied, no apparent issues yet. Is this because we are using docker or what? 

Thanks!
