### ISSUE TITLE
nextcloud 15.0.2 not working with onlyoffice integration

### ISSUE THREAD

**Issue by hm400** [nextcloud/docker#624]
docker nextcloud image "nextcloud:15.0.2" with onlyoffice/documentserver:5.2.7.2 image produces error
![screenshot from 2019-01-25 21-56-52](https://user-images.githubusercontent.com/47049792/51782887-2e2d1800-20fe-11e9-815e-a9e5e331a31c.png)
When nextcloud image is rolled back to nextcloud:14.0 (same documentserver:5.2.7.2) the integrated editor works normally. Most searches suggest this is a document server issue related to 

"The document editing service cannot connect to the document storage service at the editorConfig.callbackUrl address. Check if the Callback handler is working correctly. The document storage service must return {"error": 0} in response." 
But i'll i did was change the nextcloud image to an older version and it worked.
Any ideas?

**Comment by nrgeen** [comment]
Hello, I had the same problem. I also just assumed that it was Docker. I also noticed that my valid Let' Encrypt certificate was not displayed as completely secure. After a long search, it turned out that this was due to two missing variables in the conifg.php. I assume that these have become more important in Nextcloud 15 than they were in Nextcloud 14. 
But this all changed after I set the following variables correctly in config.php:
  overwrite.cli.url' => 'https://your.nextcloud.com',
  overwritehost => your.nextcloud.com,
  overwriteprotocol' => 'https',

**Comment by hm400** [comment]
you are excellent. This fixed my problem too. thank you.
would add - don't forget single quotes for 'overwrite' => 'your.nextcloud.com', and
you may have to add overwritehost and ovewriteprotocol variables to your config.php if there missing

**Comment by nrgeen** [comment]
> would add - don't forget single quotes for 'overwrite' => 'your.nextcloud.com', and

Thank you for pointing that out. I changed it.
