### ISSUE TITLE
Apps Persistence not fully working

### ISSUE THREAD

**Issue by n3m3s1s** [nextcloud/docker#68]
Hi everyone,
I am using this docker behind some reverse proxy as suggested with the three volumes suggested.
(.../apps .../config .../data) and persisted them on the host drive.
Nevertheless when I do this:
docker pull
docker stop nextcloud-docker
docker rm nextcloud-docker
docker run -d ... (including all the options from before)

-> All apps are disabled again. If reenabled they will come up with their old datasets, so appearently my e.g. calender gets saved as supposed but the fact that this app was enabled does not get saved.
1) Is this expected behaviour?
2) Can I persist the apps status in any way?
Cheers

**Comment by tilosp** [comment]
We changed the way you upgrade this image. The docs needs to get updated. We are working on this in #53. 
There a two thing you need to change:

1. we now use a custom apps folder `/var/www/html/custom_apps` which you should persist instead of `/var/www/html/apps`
2. the new upgrade system uses the `version.php` to detect the currently installed version. This means you need to add a persistent volume `/var/www/html` for it to upgrade properly

**Comment by n3m3s1s** [comment]
Ah I missed that one. Just to make sure: persisting /var/www/html should be enough? Wouldn't we run into problems with extra files conflicting with the security-self-check?
I'll just give that a try.

**Comment by tilosp** [comment]
No, extra files get deleted by the new update script using rsync. [docker-entrypoint.sh#L25](https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L25)
