### ISSUE TITLE
Is there a way to test new Nextcloud-Versions in a container without toching the data folder ?

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/docker#750]
Hi there,

i would like to test new nextcloud versions in a separate docker container to check if an update works fine. At the moment my approach is like this.

1. I create a copy of the database folder for the mariadb container
2. I create a copy of the custom_apps, themes, config folders of the current nextcloud container. Not the data folders because its huge :)
3. I have a second compose file which defines new containers for redis, nextcloud and mariadb using the copied folders. The new nextcloud container can use a new version of nextcloud like 16

When i mount the data folder read only nextcloud complains about that.  It would be great to have a separate read only container to check if everything works with a new version of nextcloud. Is there a way to mount the data folder read only ?

I'm happy about other approaches as well and your thoughts about that

**Comment by cowai** [comment]
@hriekehof Maybe you can use https://github.com/trapexit/mergerfs as a middle layer to make writes to the data folder go to /tmp or something?

**Comment by Heracles31** [comment]
Hi hriekehof,

I think you are missing something here... A service like Nextcloud requires regular backups. It is meant to host all of your data, all your activity, ... Also, a backup is not working until you successfully restored it. So take the chance and deploy an actual backup solution that you will test by doing a full restore.

Here, I created my container with 5 different volumes :
Root = /var/www/html
Config = /var/www/html/config
Apps = /var/www/html/custom_apps
Themes = /var/www/html/themes

These 4 are regular local Docker volumes

Data = /var/www/html/data

That one is an NFS share mounted from my FreeNAS server. It is actually mounted by the Docker Host as /mnt/freenas and I re-map /mnt/freenas/data as /var/www/html/data.

In a separate Docker container, I re-mount Root, Config, Apps and Themes as Read-Only volumes. I also mount another share, Backup, from my FreeNAS. From that second Docker container, I run my backup scripts from Cron or manually should I wish. The script creates the tarballs for the RO volumes and connects the Database over the network for that backup. Everything is then saved in the FreeNAS. Snapshots are taken there and replicated to an off site DR server.

Thanks to that, I can revert my entire setup to any moment I wish in my backup schedule. No matter it is to recover after a failed upgrade, corrupted or loss data or whatever reason. A complete physical destruction of the site like fire or flood is still recoverable thanks to that setup.

So I would say deploy a proper backup and restore solution and rely on it for such a case. If you do not allow yourself to rely on your backup, consider that it means you have no backups...

Good luck,

**Comment by hriekehof** [comment]
Hi,

all the docker containers run in a VM which is regularly backed up. I can also set snapshots and try out updates but when something does not work i have to revert the machine. I could also create a second vm to try out updates etc. 
But with docker i thought it would be nice to be able to just run a second container with a new instance and a read only mount of the data folder. It should be possible then that NC 15 runs in production and NC16 has the same data folder RO but its own Database and config and apps folders.

When i do this i get this error message:

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request.
> Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
> More details can be found in the server log.

You said you can mount all folders RO ?
> In a separate Docker container, I re-mount Root, Config, Apps and Themes as Read-Only volumes.

This is exactly what i would like to do but somehow it does not work for me.

This is the error message from the container log. Is it even possible to run a nextcloud container with RO on the data folder ?
<details>

Permissions can usually be fixed by giving the webserver write access to the root directory. See https://docs.nextcloud.com/server/16/go.php?to=admin-dir_permissions.,
Your data directory is not writable,
crond: USER www-data pid  66 cmd php -f /var/www/html/cron.php,
{"reqId":"BQPtepTiLRq9Mq6liGeF","level":3,"time":"2019-05-22T08:15:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fopen(\/var\/www\/html\/data\/data_dir_writability_test_5ce50505ef1b5.tmp): failed to open stream: Read-only file system at \/var\/www\/html\/lib\/private\/legacy\/util.php#795","userAgent":"--","version":"15.0.8.1"},
{"reqId":"BQPtepTiLRq9Mq6liGeF","level":3,"time":"2019-05-22T08:15:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fopen(\/var\/www\/html\/data\/nextcloud.log): failed to open stream: Read-only file system at \/var\/www\/html\/lib\/private\/Log\/File.php#139","userAgent":"--","version":"15.0.8.1"},

</details>

**Comment by Heracles31** [comment]
Hi again,

Yes, I do re-mount these volumes as RO, but not to run a second container from them... I re-mount these volumes as RO from a second container that I use as a backup agent. That second container only create the tarballs I need for backup and recovery.

Should I wish to run a clone of the production, what I do is :
--In the FreeNAS, I clone the snapshot I wish to start my clone from
--I download the corresponding tarballs (same time and date as the cloned snapshot)
--In a separate MySQL server, I restore the database
--I create a separate set of Docker volumes for the 4 tarballs
--I restore the 4 tarballs each in the appropriate volume
--I edit the config file to point the database to the separate MySQL server
--I mount the FreeNAS snapshot as the data partition
--I deploy the new NC container with the new volumes and data clone

After that, I have a cloned environment that can do read - write everywhere to everything without touching the prod. Once done with it, I can destroy everything : the second NextCloud container, the restored volumes, the restored database and the snapshot clone.

Because you rely on VM snapshot instead, you snapshot much more than what I do with only my FreeNAS snapshot.

It is not realistic to run Nextcloud from Read-Only config, etc. Just think about something like maintenance mode. To turn Maintenance Mode On and Off, Nextcloud writes the corresponding status in config.php. Should that file be RO, it would not be possible for it to go to Maintenance Mode. Apps are another example : with RO folders, how do you expect being able to add or update any apps for testing ? With a RO folder, all your apps are also RO.

You need a RW environment for testing...

Hope this helps you understand better the situation,

**Comment by hriekehof** [comment]
Ok i see that a RO environment is not possible. It would have been great though not to have a copy off all the data to test new versions. 
Some appliances like Remind are able to do that. You just create a new database and the files can be mounted read only.
This makes it very quick and easy to test new versions with production data without interfering.
