### ISSUE TITLE
I can't use external storages extension.

### ISSUE THREAD

**Issue by oDaShuTz** [nextcloud/docker#777]
My server is Debian 9.
I use `docker run -d -p 8080:80 nextcloud` to start nextcloud, and I try to activate external storages extension.
But nextcloud warns me ""smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login" is not possible. Please ask your system administrator to install it."
I try to install smbclient as follow:
`apt install smbclient libsmbclient-dev`
`pecl install smbclient`
`docker-php-ext-enable smbclient`.
But linux warns me"pecl: commond not found", "docker-php-ext-enable: commond not found".
What should I do?
Thank you for helping me solve this problem.

**Comment by flowercow** [comment]
you should run the cmd in nextcloud docker by docker exec -it  xxx bash

**Comment by oDaShuTz** [comment]
> you should run the apt cmd in nextcloud docker container by "docker exec -it xxx bash"
> just apt install smbclient, the others are not necessary

But here is other problems.

Problem 1:
I try to amount local storage, the settings is as follow: 
Folder name: virmach-root
External storage: Local
Authentication: None
Configuration: /root
Available for: All users
I saved settings succesful, but I can't see the "virmach-root" folder in Files under "All Files" tab.
I can see "virmach-root" folder under "External storages" tab, but if I click it, it will jump to "All Files" tab, and show all files except "virmach-root" folder.

Problem 2:
And if I reboot my linux,restart docker and nextcloud, it warns me ""smbclient" is not installed again, I need to re-install smbclient as your suggestion. Is there any solution to solve this problem permanently?

**Comment by oDaShuTz** [comment]
@flowercow
I try to amount "/" folder, it's successful. but "/root" folder was not shown in "/" folder.
Maybe it because linux file permission is not 777?

**Comment by oDaShuTz** [comment]
@flowercow
Nextcloud can't amount any folder I mkdir.

**Comment by flowercow** [comment]
first problem:
smbclient should not disappear if you only restart nextcloud container. but if you del and recreated the container from the image, it will be disappeared, just because smbclient is not contained in the official image. 
two way to solve this:
Ⅰ. just create a pure new container, install smbclient, del the cache caused by apt, and use commit command of docker to make the change saved into the original image.  But this way is not recommended. 
Ⅱ. build your own image based on official image by the dockerfile, you can refence to https://github.com/nextcloud/docker/tree/master/.examples using docker or docker-compose
the second problem:
first mount options in nextcloud local means file directories in the nextcloud docker container. 
if you want to mout your host directory into nextcloud you need to use samba share in host or use volume option of docker to make it to binding as a local directory in the docker container.
And there are two mount operation needed in nextcloud web interface. 
The first mout in admin settings, after that do some actions as user. 
look the left slide side of setting.

**Comment by mxkemnito** [comment]
> you should run the apt cmd in nextcloud docker container by "docker exec -it xxx bash"
> just apt install smbclient, the others are not necessary

when I use this, I get the Error: E: Unable to locate package smbclient

Anyone knows why?

**Comment by FaMux** [comment]
Check /etc/apt/sources.list, there must be a valid package list.

**Comment by mxkemnito** [comment]
Yes, that is the case.

```
# deb http://snapshot.debian.org/archive/debian/20201117T000000Z buster main
deb http://deb.debian.org/debian buster main
# deb http://snapshot.debian.org/archive/debian-security/20201117T000000Z buster/updates main
deb http://security.debian.org/debian-security buster/updates main
# deb http://snapshot.debian.org/archive/debian/20201117T000000Z buster-updates main
deb http://deb.debian.org/debian buster-updates main

```

The bug was gone when I ran:
`apt-get update`

After that, I could install smbclient like it's described the instructions.
