### ISSUE TITLE
LDAP/AD Integration Hanging on Setup

### ISSUE THREAD

**Issue by theorlandog** [nextcloud/docker#781]
Hello,
I would very much like to move from OwnCloud to NextCloud, but I am running into an issue with the ldap integration that I am having trouble debugging. Would definitely appreciate some tips or assistance.

When configuring the ldap server, the gui presents many flash messages saying that nextcloud has lost connection to the ldap server. Although, it can test a few things, like 'Test Base DN' and 'Verify Settings and Count Groups', the server reliably fails while trying to 'Verify Settings and Count Users'. Not sure how much the plugin drifts from the owncloud version, but I've never had any issues with the owncloud ldap plugin. Has always worked perfectly. 

![image](https://user-images.githubusercontent.com/14035208/59975989-a7854580-958c-11e9-9330-3a001ec1167c.png)

Thank you for any help you may be able to provide.

-Jamie

**Comment by joshtrichards** [comment]
Hi @theorlandog - This issue may have gotten overlooked because it sounds like a general support request. I hope you were able to find help through a different channel. This channel is only for bug reports and enhancement requests in the official community Nextcloud Docker image, but not for Nextcloud itself. Your query sounds like troubleshooting/configuration/local environment topic to bring up at the [Nextcloud Help Forum](https://help.nextcloud.com).

If you agree, please close out this Issue. Thanks!
