### ISSUE TITLE
External storage can’t delete folders 

### ISSUE THREAD

**Issue by vipera7** [nextcloud/docker#786]
I created a clean container and I want to use the application external storage. I managed to configure successfully a local storage using the following command : 

    mount_id=$(docker exec --user 1000 nextcloud php occ files_external:create Home local null::null -c datadir=/var/www/data --output=json)
    docker exec --user 1000 nextcloud php occ files_external:applicable --add-user=foo "$mount_id"

I can create/move/copy folder and files but when I want to delete  a created folder I got the following error :

> Error deleting file "folderfoo".

It's says it's a file but actually it was a folder. After refreshing the browser the folder is deleted. By the way I can successfully delete files.
I'm using this image https://hub.docker.com/_/nextcloud/
I added the right user permission on the docker container and the data folder.

I don't know what I'm supposed to do, thanks for any help

**Comment by viruslab1** [comment]
I have the same problem.

**Comment by viruslab1** [comment]
I solve this problem by moving "external folder" to another physical hard drive. Problem magicly solved.

**Comment by vipera7** [comment]
@viruslab1 Thanks for the feedback, but I'm working on a single hard drive

**Comment by AndreaPro** [comment]
> I solve this problem by moving "external folder" to another physical hard drive. Problem magicly solved.

You are right, thanks for the workaround. By the way would be nice to have a fix instead of a workaround because is not doable on every system

**Comment by joshtrichards** [comment]
Hi folks. Hopefully you figured out a solution or found one through another channel. 

In general this is impossible to answer since additional information would be needed (namely how you've mounted the local volume from your host within your container not just Nextcloud and the entries from your `nextcloud.log` when you see those errors).

That said, this channel is for reporting bugs in the community Docker image. This looks like a support matter so the best channel for follow-up on configuration matters and general troubleshooting assistance is the [Nextcloud Help Forum](https://help.nextcloud.com).

Since this issue is >3 years old and hasn't had any recent traffic I'm going to close it out.
