### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by monreal** [nextcloud/docker#918]
Latest changes to nginx.conf result in the following error:

502 Bad Gateway
nginx/1.17.3

**Comment by joshtrichards** [comment]
Hi @monreal - Thanks for the report. I'm assuming you were referring to the changes made in #912 (since they were a couple hours before you sent this in). Not sure how you applied the changes or if it was a new install or what. Anyhow it's been a LONG time and I suspect this issue is no longer relevant and you've since addressed your situation.

If you agree, please close this Issue out. Thanks!

**Comment by monreal** [comment]
No longer using Nextcloud
