### ISSUE TITLE
MariaDB, Insecure, Apache Example is No Longer Working

### ISSUE THREAD

**Issue by ShiromMakkad** [nextcloud/docker#951]
When I log in, it says that it cannot find the database. I'm using the exact code from the Github and I've set the database password.

The Postgress version works great, so I assume the issue is with the MariaDB docker image. It probably got changed in a recent update.

I'm just going to stick to Postgress, but I though you should know that the example is broken.

**Comment by jensamberg** [comment]
Hello,

I have the same problem MariaDB is not working

**Comment by ngoonee** [comment]
Not just insecure, it's all the mariadb examples which aren't working. The version of mariadb should be specified in the example docker-compose.yml (IMHO).

**Comment by jensamberg** [comment]
I tried MariaDB 10.3 doesn’t work. Do anybody know the last working tag ?

**Comment by bigr4232** [comment]
It also is not working for me. Has anyone figured out a solution to this?

**Comment by ShiromMakkad** [comment]
I got this same issue on jc21/nginx-proxy-manager. I fixed it by going to version 10.4.5, but for the downgrade to work, you had to delete all the persisted data inside the volumes. I'm not sure if @jensamberg did that, but it might be worth a shot here.

**Comment by jensamberg** [comment]
@ShiromMakkad I tried a fresh installation. So I had no persist data. I also discovered that the MariaDB Image does not read the environment. Do you think the Issue is in the MariaDB Container?

**Comment by blackerking** [comment]
Got simmiliar problems with linuxserver/mariadb and linuxserver/nextcloud . I had to add a database and a user with privileges. Entering this information at start works. But i also had a timeout and I had to add the variable installed => true inside the config.

**Comment by Sincopy** [comment]
It seems there's several regressions when doing first instantiation of MariaDB. One is related to the TZTIME tool timing out, but there's a workaround for that.
The second hurdle I found was (also on first instantiation) that writing to ibtmpl for some reason also took a very long time (10-15s) and timed out, even though it's only a 12mb file and dd-ing to the drive normally get's me about 400mbps. I gave up on mariadb after that.

Please also note that the yml files won't even work when replacing mariadb with mysql:latest, since none of the nextcloud images seem to include PHP7.4, required for the cached_sha256, which is default since mysql:8.
All in all, it would be smart to have the yml files pin the version of the images they were tested with, so at least examples work as published.

**Comment by J0WI** [comment]
See https://github.com/docker-library/mariadb/issues/262
